### PR TITLE
logback: log stack trace

### LINKED ISSUE #2735: Exceptions logged with Logback + SLF4J don't show up in Stackdriver
I'm using the Logback + SLF4J logging configuration described in the official documentation [here](https://cloud.google.com/logging/docs/setup/java).
Everything works fine with simple log messages like:
```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
...
private static final Logger logger = LoggerFactory.getLogger(MyClass.class);
...
logger.info("Hello world");
```

The problem appears when I try to log exceptions like this:
```java
logger.error("Something went wrong:", ex);
```

I see only my description message in Stackdriver but not the stack trace from the provided exception.
What can be the problem here?

### PR DESCRIPTION
**Pull request by pongad**
Fixes #2735.

### CODE REVIEW

File: google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java [hunk 1]
```diff
@@ -206,10 +206,15 @@ Logging getLogging() {
   }
 
   private LogEntry logEntryFor(ILoggingEvent e) {
-    String payload = e.getFormattedMessage();
+    StringBuilder payload = new StringBuilder(e.getFormattedMessage());
+    for (StackTraceElement stackEl : e.getCallerData()) {
```
Comment (jabubake) [inline google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java]: is `e.getCallerData()` null safe ?

Comment (garrettjonesgoogle) [inline google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java]: `element` or `stackElement` would be more idiomatic for the variable name

Comment (pongad) [reply google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java]: Done

Comment (pongad) [reply google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java]: It seems to be, but the documentation never explicitly stated this. I'll add a check just in case.

**Comment by pongad** [comment]
@jabubake I'm sorry. Looking at this closer, I don't think this is right. The `getCallerData` returns the trace of the running thread, not of the exception. I don't see a way to get exception trace out of `ILoggingEvent`. Can you advise?

**Comment by jabubake** [comment]
`ILoggingEvent` has a `getThrowableProxy` method.
see examples here : http://www.javased.com/?api=ch.qos.logback.classic.spi.IThrowableProxy

**Comment by pongad** [comment]
@garrettjonesgoogle @jabubake PTAL. I think this actually works now :)

**Comment by pongad** [comment]
@garrettjonesgoogle @jabubake Ping

File: google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java [hunk 2]
```diff
@@ -231,6 +230,34 @@ private LogEntry logEntryFor(ILoggingEvent e) {
     return builder.build();
   }
 
+  @InternalApi
```
Comment (garrettjonesgoogle) [inline google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java]: Add text to the annotation ("Visible for testing")

File: google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java [hunk 3]
```diff
@@ -231,6 +230,34 @@ private LogEntry logEntryFor(ILoggingEvent e) {
...
+    if (throwProxy == null) {
+      return;
+    }
+    payload
+        .append(prefix)
+        .append(throwProxy.getClassName())
+        .append(": ")
+        .append(throwProxy.getMessage())
+        .append('\n');
+    StackTraceElementProxy[] trace = throwProxy.getStackTraceElementProxyArray();
```
Comment (garrettjonesgoogle) [inline google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java]: Just as a sanity check, do we know that this is a stable API that we are using? (Or maybe it doesn't matter since google-cloud-logging-logback is alpha...)

Comment (pongad) [reply google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java]: I believe it is stable. We depend on version `1.2.3`.

File: google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java (hunk 2 above)
Comment (pongad) [reply google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java]: Done
