### PR TITLE
Translate SocketTimeoutException to retryable service exception

### LINKED ISSUE #410: We should retry on read/connection timeout.
The `ExceptionHandler` of datastore and storage should be configured to retry on read/connection timeouts.

### PR DESCRIPTION
**Pull request by mziccard**
This fixes #410 by translating `SocketTimeoutException` to retryable service-specific exceptions.

### CODE REVIEW

File: gcloud-java-datastore/src/main/java/com/google/gcloud/spi/DefaultDatastoreRpc.java [hunk 1]
```diff
@@ -121,9 +122,15 @@ private static DatastoreRpcException translate(DatastoreException exception) {
...
-        ? new DatastoreRpcException(reason)
-        : new DatastoreRpcException("Unknown", exception.getCode(), false, message);
+    if (reason != null) {
+      return new DatastoreRpcException(reason);
+    } else {
+      boolean retryable = false;
+      if (exception.getCause() instanceof SocketTimeoutException) {
+        retryable = true;
+      }
+      return new DatastoreRpcException("Unknown", exception.getCode(), retryable, message);
```
Comment (aozarov) [inline gcloud-java-datastore/src/main/java/com/google/gcloud/spi/DefaultDatastoreRpc.java]: "Unknown" -> "Request timeout" ?

**Comment by mziccard** [comment]
Fixed
