### PR TITLE
Pass through header provider in BQ storage client settings.

### LINKED ISSUE #4737: BigQuery storage settings don't propagate the user-agent header
This doesn't work:

```java
      BigQueryStorageSettings settings =
          BigQueryStorageSettings.newBuilder()
              .setHeaderProvider(USER_AGENT_HEADER_PROVIDER)
              .build();
```

This does:

```java
      BigQueryStorageSettings settings =
          BigQueryStorageSettings.newBuilder()
              .setTransportChannelProvider(
                  BigQueryStorageSettings.defaultGrpcTransportProviderBuilder()
                      .setHeaderProvider(USER_AGENT_HEADER_PROVIDER)
                      .build())
              .build();
```

This seems wrong.

### PR DESCRIPTION
**Pull request by kmjung**
This change modifies the enhanced stub for the BigQuery storage
client to pass through the user-specified header provider to the
storage settings base class at creationt ime. This addresses an
issue where user-specified headers were being ignored when creating
a client object.

Fixes #4737

### CODE REVIEW

**Comment by kmjung** [comment]
Cc: @JesseLovelace

File: google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/ResourceHeaderTest.java [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+
+  private static final String TEST_HEADER_NAME = "simple-header-name";
+  private static final String TEST_HEADER_VALUE = "simple-header-value";
+  private static final Pattern TEST_PATTERN = Pattern.compile(".*" + TEST_HEADER_VALUE + ".*");
+
+  private InProcessServer<?> server;
+  private LocalChannelProvider channelProvider;
+  private BigQueryStorageClient client;
+
+  @Before
```
Comment (ajaaym) [inline google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/ResourceHeaderTest.java]: Please use @BeforeClass and @Afterclass below.

Comment (kmjung) [reply google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/ResourceHeaderTest.java]: This is taken verbatim from https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/ResourceHeaderTest.java -- do you want me to update that file as well?

Comment (kmjung) [reply google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/ResourceHeaderTest.java]: Scratch that -- the local channel provider stores the outgoing headers and has to be regenerated for each test.

Comment (kmjung) [reply google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/ResourceHeaderTest.java]: Moved the server setup to the class level, at least.

File: google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/ResourceHeaderTest.java [hunk 2]
```diff
@@ -0,0 +1,177 @@
+/*
+ * Copyright 2018 Google LLC
```
Comment (sduskis) [inline google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/ResourceHeaderTest.java]: s/2018/2019

Comment (kmjung) [reply google-cloud-clients/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/stub/ResourceHeaderTest.java]: Done.

**Comment by kmjung** [comment]
@sduskis any idea when this might get merged?
