### PR TITLE
Fix ConcurrentModificationException when flushing async log messages

### LINKED ISSUE #2207: ConcurrentModificationException when flushing logs using Synchronicity.ASYNC
The code below results in a couple of ConcurrentModificationExceptions when run:

    public class Repro {

      private static final String PROJECT_ID = "MYPROJECT";
      private static final String LOG_NAME = "MYLOGNAME";

      public static void main(String... args) throws InterruptedException {
        Logging logging = LoggingOptions.getDefaultInstance().getService();
        logging.setWriteSynchronicity(Synchronicity.ASYNC);

        MonitoredResource monitoredResource =
            MonitoredResourceUtil.getResource(PROJECT_ID, null);

        final LogEntry entry = LogEntry.newBuilder(Payload.StringPayload.of("Hello"))
            .setLogName(LOG_NAME)
            .setSeverity(Severity.ERROR)
            .setResource(monitoredResource)
            .build();

        Thread[] threads = new Thread[10];
        for (int i = 0; i < threads.length; i++) {
          threads[i] = new Thread(() -> {
            logging.write(Collections.singleton(entry));
          });
          threads[i].start();
        }

        for (int i = 0; i < threads.length; i++) {
          threads[i].join();
        }
      }
    }

Here is the stacktrace:

    java.util.ConcurrentModificationException
        at java.util.IdentityHashMap$KeySet.toArray(IdentityHashMap.java:1030)
        at java.util.IdentityHashMap$KeySet.toArray(IdentityHashMap.java:1015)
        at java.util.Collections$SetFromMap.toArray(Collections.java:5463)
        at java.util.ArrayList.addAll(ArrayList.java:577)
        at com.google.cloud.logging.LoggingImpl.flush(LoggingImpl.java:539)
        at com.google.cloud.logging.LoggingImpl.write(LoggingImpl.java:525)
        at com.spotify.logback.Repro.lambda$main$0(Repro.java:35)
        at java.lang.Thread.run(Thread.java:745)

It looks like there is a missing `synchronized(writeLock)` around this line: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java#L583

### PR DESCRIPTION
**Pull request by stalar**
A missing synchronized statement when adding to pendingWrites cause
ConcurrentModificationExceptions in the flush() method when the
pendingWrites are copied to writesToFlush.

Fixes #2207.

### CODE REVIEW

**Comment by stalar** [comment]
I signed it! 

Or at least Spotify signed it and I have tried to commit using my @spotify.com email address, but it does not look like it is working?

File: google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingImplTest.java [hunk 1]
```diff
@@ -1448,5 +1449,44 @@ public void run() {
...
+    final AtomicInteger exceptions = new AtomicInteger(0);
+    for (int i = 0; i < threads.length; i++) {
+      threads[i] = new Thread() {
+        @Override
+        public void run() {
+          try {
+            logging.write(ImmutableList.of(LOG_ENTRY1));
+            logging.flush();
+          } catch (Exception ex) {
+            ex.printStackTrace();
```
Comment (michaelbausor) [inline google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingImplTest.java]: Can we remove the `printStackTrace()` call as suggested by codacy?

Comment (stalar) [inline google-cloud-logging/src/test/java/com/google/cloud/logging/LoggingImplTest.java]: Sure, but it does make the test harder to debug if it fails.

**Comment by stalar** [comment]
Thanks for taking a look at the PR!


About the CLA:
* My spotify email address is added to my GitHub account (although it wasn't when I created the commit and the pull request).
* I have been added to the group of authorized contributors for Spotify

Should I just try a new PR?

**Comment by stalar** [comment]
Thanks googlebot!

**Comment by JoshuaFox** [comment]
Bug still occurs for me
Using `com.google.cloud:google-cloud-logging:jar:1.16`
Flexible Environment GA
```

java.util.ConcurrentModificationException at
 java.util.IdentityHashMap$KeySet.toArray(IdentityHashMap.java:1037) at
 java.util.IdentityHashMap$KeySet.toArray(IdentityHashMap.java:1015) at
 java.util.Collections$SetFromMap.toArray(Collections.java:5463) at
 java.util.ArrayList.addAll(ArrayList.java:577) at
 com.google.cloud.logging.LoggingImpl.flush(LoggingImpl.java:539) at
 com.google.cloud.logging.LoggingImpl.write(LoggingImpl.java:525) at
 com.google.cloud.logging.LoggingHandler.publish(LoggingHandler.java:273) at
 java.util.logging.Logger.log(Logger.java:738) at
 java.util.logging.Logger.doLog(Logger.java:765) at
 java.util.logging.Logger.log(Logger.java:788) at
 java.util.logging.Logger.severe(Logger.java:1464) a
```
