### PR TITLE
Fix StorageImpl.signUrl with object names starting with /

### LINKED ISSUE #1006: StorageImpl.signUrl generates invalid URLs for objects names with leading /
The generated URL contains zero-chars.

The problem is probably here: https://github.com/GoogleCloudPlatform/gcloud-java/compare/master...clementdenis:patch-1

The method should either reject object names leading slash, or handle them correctly.

### PR DESCRIPTION
**Pull request by mziccard**
This fixes #1006. This PR cherry-picks @clementdenis's commit from #1008 and adds a unit test

### CODE REVIEW

File: gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java [hunk 1]
```diff
@@ -1156,6 +1156,36 @@ public void testSignUrl() throws NoSuchAlgorithmException, InvalidKeyException,
...
+            .append("?GoogleAccessId=").append(ACCOUNT).append("&Expires=").append(42L + 1209600)
+            .append("&Signature=").toString();
+    System.out.println(stringUrl);
+    System.out.println(expectedUrl);
+    assertTrue(stringUrl.startsWith(expectedUrl));
+    String signature = stringUrl.substring(expectedUrl.length());
+
+    StringBuilder signedMessageBuilder = new StringBuilder();
+    signedMessageBuilder.append(HttpMethod.GET).append('\n').append('\n').append('\n')
+        .append(42L + 1209600).append('\n').append("/").append(BUCKET_NAME1).append(blobName);
```
Comment (mziccard) [inline gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java]: Codacy Issue found: [Avoid appending characters as strings in StringBuffer.append.](https://www.codacy.com/app/mziccard/gcloud-java/file/2579566087/issues/source?bid=3123103&fileBranchId=3302344#l1179)

Comment (mziccard) [inline gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java]: Codacy Issue found: [StringBuffer (or StringBuilder).append is called 2 consecutive times with literal Strings. Use a single append with a single combined String.](https://www.codacy.com/app/mziccard/gcloud-java/file/2579566087/issues/source?bid=3123103&fileBranchId=3302344#l1179)

File: gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java [hunk 2]
```diff
@@ -1156,6 +1156,36 @@ public void testSignUrl() throws NoSuchAlgorithmException, InvalidKeyException,
...
+    ServiceAccountAuthCredentials authCredentials =
+        ServiceAccountAuthCredentials.createFor(ACCOUNT, privateKey);
+    storage = options.toBuilder().authCredentials(authCredentials).build().service();
+    URL url = storage.signUrl(BlobInfo.builder(BUCKET_NAME1, blobName).build(), 14, TimeUnit.DAYS);
+    String stringUrl = url.toString();
+    String expectedUrl =
+        new StringBuilder("https://storage.googleapis.com/").append(BUCKET_NAME1).append(blobName)
+            .append("?GoogleAccessId=").append(ACCOUNT).append("&Expires=").append(42L + 1209600)
+            .append("&Signature=").toString();
+    System.out.println(stringUrl);
```
Comment (mziccard) [inline gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java]: Codacy Issue found: [System.out.println is used](https://www.codacy.com/app/mziccard/gcloud-java/file/2579566087/issues/source?bid=3123103&fileBranchId=3302344#l1172)

File: gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java [hunk 3]
```diff
@@ -1156,6 +1156,36 @@ public void testSignUrl() throws NoSuchAlgorithmException, InvalidKeyException,
...
+    System.out.println(expectedUrl);
```
Comment (mziccard) [inline gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java]: Codacy Issue found: [System.out.println is used](https://www.codacy.com/app/mziccard/gcloud-java/file/2579566087/issues/source?bid=3123103&fileBranchId=3302344#l1173)

File: gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java [hunk 4]
```diff
@@ -1136,17 +1136,44 @@ public void testSignUrl() throws NoSuchAlgorithmException, InvalidKeyException,
...
+    ServiceAccountAuthCredentials authCredentials =
+        ServiceAccountAuthCredentials.createFor(ACCOUNT, privateKey);
+    storage = options.toBuilder().authCredentials(authCredentials).build().service();
+    URL url = storage.signUrl(BlobInfo.builder(BUCKET_NAME1, blobName).build(), 14, TimeUnit.DAYS);
+    String stringUrl = url.toString();
+    String expectedUrl = new StringBuilder("https://storage.googleapis.com/").append(BUCKET_NAME1)
+        .append(blobName).append("?GoogleAccessId=").append(ACCOUNT).append("&Expires=")
+        .append(42L + 1209600).append("&Signature=").toString();
+    System.out.println(stringUrl);
+    System.out.println(expectedUrl);
```
Comment (mziccard) [inline gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java]: Codacy Issue found: [System.out.println is used](https://www.codacy.com/app/mziccard/gcloud-java/file/2579881382/issues/source?bid=3123103&fileBranchId=3302344#l1170)

File: gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java [hunk 5]
```diff
@@ -1136,17 +1136,44 @@ public void testSignUrl() throws NoSuchAlgorithmException, InvalidKeyException,
...
+    EasyMock.replay(storageRpcMock);
+    ServiceAccountAuthCredentials authCredentials =
+        ServiceAccountAuthCredentials.createFor(ACCOUNT, privateKey);
+    storage = options.toBuilder().authCredentials(authCredentials).build().service();
+    URL url = storage.signUrl(BlobInfo.builder(BUCKET_NAME1, blobName).build(), 14, TimeUnit.DAYS);
+    String stringUrl = url.toString();
+    String expectedUrl = new StringBuilder("https://storage.googleapis.com/").append(BUCKET_NAME1)
+        .append(blobName).append("?GoogleAccessId=").append(ACCOUNT).append("&Expires=")
+        .append(42L + 1209600).append("&Signature=").toString();
+    System.out.println(stringUrl);
```
Comment (mziccard) [inline gcloud-java-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java]: Codacy Issue found: [System.out.println is used](https://www.codacy.com/app/mziccard/gcloud-java/file/2579881382/issues/source?bid=3123103&fileBranchId=3302344#l1169)
