### PR TITLE
Firestore: Fix FieldValue.arrayUnion() accept POJO.

### LINKED ISSUE #5622: Firestore: update with arrayUnion doesn't accept POJO
Writing this POJO works in other APIs but fails in ArrayUnion updates.

#### Exception thrown
java.lang.reflect.InvocationTargetException: Cannot convert org.wizgraph.backend.data.common.ResourcePointer@7f6c897b to Firestore Value

#### Environment details
Java version: 8
Firestore maven version:
```xml
<groupId>com.google.cloud</groupId>
<artifactId>google-cloud-firestore</artifactId>
<version>1.10.0</version>
```

#### Code example
```java
  public static void updateStarredFramework(
      DocumentReference ref, String fieldName, ResourcePointer ptr) throws Exception {
    FieldValue updateValue = FieldValue.arrayUnion(ptr);
    ref.update(fieldName, updateValue).get();
  }
```

### PR DESCRIPTION
**Pull request by pmakani**
Fixes #5622

### CODE REVIEW

**Comment by BenWhitehead** [comment]
This looks like it's okay to me. What do you think @schmidt-sebastian?

File: google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldValue.java [hunk 1]
```diff
@@ -153,8 +153,9 @@ FieldTransform toProto(FieldPath path) {
       ArrayValue.Builder encodedElements = ArrayValue.newBuilder();
 
       for (Object element : elements) {
+        Object data = CustomClassMapper.convertToPlainJavaTypes(element);
```
Comment (schmidt-sebastian) [inline google-cloud-clients/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldValue.java]: Can you make the same change for `ArrayRemoveFieldValue`?

File: google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java [hunk 2]
```diff
@@ -169,4 +181,86 @@ public void incrementEquals() {
...
+                ImmutableList.<List<String>>of(ImmutableList.<String>of("test-1", "test-2")),
+                ImmutableMap.<String, Map<String, String>>of(
+                    "test-1", ImmutableMap.of("test-value1", "test-value2")),
+                ImmutableList.<Map<String, String>>of(
+                    ImmutableMap.<String, String>of("test", "test-value"))));
+    WriteResult writeResult = doc.update("foo", fieldValue).get();
+    assertEquals(Timestamp.ofTimeSecondsAndNanos(0, 0), writeResult.getUpdateTime());
+  }
+
+  private static class TestPoJo {
```
Comment (schmidt-sebastian) [inline google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java]: Would it be possible to just use https://github.com/googleapis/google-cloud-java/blob/2b28ae1c1bfdeea660e3883cc6940dbe3fcc60d0/google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java#L124 or https://github.com/googleapis/google-cloud-java/blob/2b28ae1c1bfdeea660e3883cc6940dbe3fcc60d0/google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/LocalFirestoreHelper.java#L143?

If not, can you move this class to `LocalFirestoreHelper`?

File: google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java [hunk 3]
```diff
@@ -169,4 +181,86 @@ public void incrementEquals() {
...
+            new TestPoJo(
+                1,
+                "name,",
+                ImmutableList.<List<String>>of(ImmutableList.<String>of("test-1", "test-2")),
+                ImmutableMap.<String, Map<String, String>>of(
+                    "test-1", ImmutableMap.of("test-value1", "test-value2")),
+                ImmutableList.<Map<String, String>>of(
+                    ImmutableMap.<String, String>of("test", "test-value"))));
+    WriteResult writeResult = doc.update("foo", fieldValue).get();
+    assertEquals(Timestamp.ofTimeSecondsAndNanos(0, 0), writeResult.getUpdateTime());
```
Comment (schmidt-sebastian) [inline google-cloud-clients/google-cloud-firestore/src/test/java/com/google/cloud/firestore/FirestoreTest.java]: I know it would be a lot more code, but to me this test would be more valuable if it verified the generated proto.

**Comment by pmakani** [comment]
@schmidt-sebastian PTAL

**Comment by BenWhitehead** [comment]
@pmakani Thanks for the contribution!
