### PR TITLE
storage: speed up IT

### LINKED ISSUE #3019: Storage integration tests failing
Last 8 commits have failed. https://circleci.com/gh/GoogleCloudPlatform/google-cloud-java/2684

### PR DESCRIPTION
**Pull request by pongad**
We create fewer blobs since the basic case is already
tested by other ITs.

Fixes #3019, hopefully.

### CODE REVIEW

File: google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java [hunk 1]
```diff
@@ -410,45 +410,42 @@ public void testListBlobsEmptySelectedFields() throws InterruptedException {
...
           Storage.BlobListOption.fields(),
           Storage.BlobListOption.userProject("fakeBillingProjectId"));
       fail("Expected bad user project error.");
     } catch (StorageException e) {
       assertTrue(e.getMessage().contains("User project specified in the request is invalid"));
     }
-    while (Iterators.size(page.iterateAll().iterator()) != 2) {
+
+    String projectId = remoteStorageHelper.getOptions().getProjectId();
+    for (; ; ) {
```
Comment (garrettjonesgoogle) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java]: Isn't it more common to do `while(true)` in Java?

File: google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java [hunk 2]
```diff
@@ -410,45 +410,42 @@ public void testListBlobsEmptySelectedFields() throws InterruptedException {
...
+      Page<Blob> page =
+          storage.list(
+              BUCKET,
+              Storage.BlobListOption.prefix("test-list-blobs-empty-selected-fields-blob"),
+              Storage.BlobListOption.fields(),
+              Storage.BlobListOption.userProject(projectId));
+      int size = Iterators.size(page.iterateAll().iterator());
+      if (size == 1) {
```
Comment (garrettjonesgoogle) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java]: This check feels weird - what if it keeps returning `2` or something like that?

File: google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java (hunk 1 above)
Comment (pongad) [reply google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java]: I don't know. I like `for` because it has fewer characters, but `while` is fine with me.

File: google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java (hunk 2 above)
Comment (pongad) [reply google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java]: Done

**Comment by pongad** [comment]
@garrettjonesgoogle PTAL. I also slightly increased the time limit. Hopefully it flakes less.

File: google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java (hunk 1 above)
Comment (garrettjonesgoogle) [reply google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java]: Characters, schmaracters. It increases the token count, which I feel is worse :-P

File: google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java [hunk 3]
```diff
@@ -434,16 +434,19 @@ public void testListBlobRequesterPays() throws InterruptedException {
...
               Storage.BlobListOption.userProject(projectId));
-      int size = Iterators.size(page.iterateAll().iterator());
-      if (size == 1) {
-        break;
+      List<Blob> blobs = Lists.newArrayList(page.iterateAll());
+      // If the list is empty, maybe the blob isn't visible yet; wait and try again.
+      // Otherwise, expect one blob, since we only put in one above.
+      if (!blobs.isEmpty()) {
+        assertThat(blobs).hasSize(1);
+        return;
```
Comment (garrettjonesgoogle) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java]: Maybe `break` instead, in case we want to add something after the loop?

Comment (pongad) [reply google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java]: Done
