### PR TITLE
fix(java-core): capturing startup logs and writing them to the logger incase end of stream reached

### LINKED ISSUE #9097: BlockingProcessStreamReader.java doesn't log the error text and silently exits
BlockingProcessStreamReader.java is a separate thread which checks for `blockUntil` text to appear  in it's constructor.
https://github.com/googleapis/java-core/blob/main/google-cloud-core/src/main/java/com/google/cloud/testing/BlockingProcessStreamReader.java#L47-L61

In cases where   process is abruptly closed and resulted in non zero exit code, BlockingProcessStreamReader.java doesn't log the startup logs(which may contain the error information). This causes confusion to the end user.

**Steps to reproduce**
- Run `gcloud beta emulators datastore startss` (notice the typo in command) to check the error text we get on stdout.
```
➜  java-core git:(gh_issue_1038) ✗ gcloud beta emulators datastore startss
ERROR: (gcloud.beta.emulators.datastore) Invalid choice: 'startss'.
Maybe you meant:
  gcloud beta emulators datastore start
  gcloud beta emulators datastore env-init
  gcloud beta emulators datastore env-unset
  gcloud beta emulators bigtable start
  gcloud beta emulators firestore start
  gcloud beta emulators pubsub start

To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS
```
- Execute below code and we can see that nothing is logged now.

```java
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Logger;

public class Playground {

  public static void main(String[] args) throws IOException, InterruptedException {

    Process process = CommandWrapper.create()
        .setCommand(Arrays.asList("gcloud beta emulators datastore startss".split(" "))) // notice the typo in command
        .setRedirectErrorStream().start();
    BlockingProcessStreamReader blockingProcessStreamReader = BlockingProcessStreamReader.start(
        "test-playground", process.getInputStream(), "blockUntilOutput",
        Logger.getLogger(Playground.class.getName()));

    blockingProcessStreamReader.join();

    System.out.printf("Subprocess exit code: %d%n", process.exitValue()); // should print non zero value
  }

}
```

_Ref: Similar issue happened in https://github.com/googleapis/java-datastore/issues/355._

### PR DESCRIPTION
**Pull request by jainsahab**
fixes #9097

### CODE REVIEW

**Comment by suztomo** [comment]
Thank you for moving PR here.

Using local (snapshot) build, Did you confirm this pull request fixes the “Playground” class execution written in the issue?

**Comment by jainsahab** [comment]
> Using local (snapshot) build, did you confirm this pull request fixes the “Playground” class execution written in the issue?

Hi @suztomo , Yes here it is.

image

File: java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogAggregator.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+ */
+
+package com.google.cloud.testing;
+
+import java.util.logging.Level;
+import java.util.logging.Logger;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+public class StartupLogAggregator {
```
Comment (suztomo) [inline java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogAggregator.java:24]:
```suggestion
class StartupLogAggregator {
```

Can this be package default?

Comment (suztomo) [inline java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogAggregator.java:24]: Can you add javadoc explaining why this class is helpful?

**Comment by suztomo** [comment]
lint is also failing.

File: java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogRecorder.java [hunk 2]
```diff
@@ -21,18 +21,27 @@
 import java.util.regex.Matcher;
 import java.util.regex.Pattern;
 
-public class StartupLogAggregator {
+/**
+ * This class records the logs in memory and flush them onto the {@link java.util.logging.Logger}
```
Comment (suztomo) [inline java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogRecorder.java:25]: Can you add why/when this is helpful? (the reason why you had to write this.)

Comment (jainsahab) [reply java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogRecorder.java:25]: This seems like a standalone component so i have just described 'record' and 'flush' part here. With regards to "why?" part, I've put reasoning in `BlockingProcessStreamReader.java` where this recorder is required. Let me know if that works.

File: java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogAggregator.java (hunk 1 above)
Comment (jainsahab) [reply java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogAggregator.java]: fixed.

File: java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogRecorder.java (hunk 2 above)
Comment (suztomo) [reply java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogRecorder.java:25]: The current javadoc just explains implementation (what it does). It's failing to explain why it's helpful for "Startup" (as in the class name).

Comment (jainsahab) [reply java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogRecorder.java]: Thanks for pointing this out @suztomo ,  i agree startup is not the right word for this independent component when it can be used in other non-startup use cases. I've renamed it, and also put that as an example in javadoc.

File: java-core/google-cloud-core/src/main/java/com/google/cloud/testing/LogRecorder.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+import java.util.logging.Level;
+import java.util.logging.Logger;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+/**
+ * This class records the logs in memory and flush them onto the {@link java.util.logging.Logger}
+ * when {@link #flush()} method is called.
+ *
+ * <p>This component is useful to hold logs for some time and flush them if needed. For example, we
```
Comment (suztomo) [inline java-core/google-cloud-core/src/main/java/com/google/cloud/testing/LogRecorder.java:28]: Nice. Thank you.

**Review by suztomo — APPROVED** [review]

File: java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogAggregator.java (hunk 1 above)
Comment (jainsahab) [reply java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogAggregator.java]: fixed and hence resolving this.

File: java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogRecorder.java (hunk 2 above)
Comment (jainsahab) [reply java-core/google-cloud-core/src/main/java/com/google/cloud/testing/StartupLogRecorder.java]: fixed and hence resolving this.

File: java-core/google-cloud-core/src/main/java/com/google/cloud/testing/LogRecorder.java [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+    if (hasLevel(logLine)) {
+      String stripLevel = logLine.split(":")[1].trim();
+      this.logs.append(stripLevel);
+    } else {
+      this.logs.append(logLine);
+    }
+    this.logs.append(System.getProperty("line.separator"));
+  }
+
+  /** Flush all the logs to the underlying {@link java.util.logging.Logger}. */
```
Comment (suztomo) [inline java-core/google-cloud-core/src/main/java/com/google/cloud/testing/LogRecorder.java:59]:
```suggestion
  /** Flushes all the logs to the underlying {@link java.util.logging.Logger}. */
```

The summary fragment https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment
