### PR TITLE
Preventing logging re-entrance at FINE level

### LINKED ISSUE #1386: LoggingHandler is re-entrant when logging FINE
When using the LoggingHandler with logging turned up to FINE, it becomes re-entrant causing either an error or a stack overflow.

This appears due to the fact that classes used to implement LoggingHandler are themselves instrumented with Java Util Logging!   Examples I have found are `io.netty` (first stack trace below)
and `HttpURLConnection` (second stack trace using a cut/paste of LoggingHandler to com.google.cloud.runtimes.jetty9.LoggingHandler as I'm working on Issue #1329

```
Nov 10, 2016 5:57:44 PM com.google.cloud.runtimes.jetty9.StackDriverLogging init
INFO: test info
Nov 10, 2016 5:57:45 PM io.netty.util.internal.logging.InternalLoggerFactory newDefaultFactory
FINE: Using java.util.logging as the default logging framework
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.grpc.netty.Utils$DefaultEventLoopGroupResource.create(Utils.java:187)
	at io.grpc.netty.Utils$DefaultEventLoopGroupResource.create(Utils.java:171)
	at io.grpc.internal.SharedResourceHolder.getInternal(SharedResourceHolder.java:124)
	at io.grpc.internal.SharedResourceHolder.get(SharedResourceHolder.java:94)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:311)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:280)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:230)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:239)
	at com.google.api.gax.grpc.ServiceApiSettings$Builder$3.getOrBuildChannel(ServiceApiSettings.java:349)
	at com.google.cloud.logging.spi.v2.ConfigServiceV2Api.<init>(ConfigServiceV2Api.java:155)
	at com.google.cloud.logging.spi.v2.ConfigServiceV2Api.create(ConfigServiceV2Api.java:145)
	at com.google.cloud.logging.spi.DefaultLoggingRpc.<init>(DefaultLoggingRpc.java:140)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:68)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:62)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:491)
	at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:96)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:43)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:38)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:478)
	at com.google.cloud.logging.LoggingHandler.getLogging(LoggingHandler.java:276)
	at com.google.cloud.logging.LoggingHandler.write(LoggingHandler.java:351)
	at com.google.cloud.logging.LoggingHandler.flush(LoggingHandler.java:357)
	at com.google.cloud.logging.LoggingHandler.publish(LoggingHandler.java:292)
	at java.util.logging.Logger.log(Logger.java:738)
	at io.netty.util.internal.logging.JdkLogger.log(JdkLogger.java:606)
	at io.netty.util.internal.logging.JdkLogger.debug(JdkLogger.java:186)
	at io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(InternalLoggerFactory.java:62)
	at io.netty.util.internal.logging.InternalLoggerFactory.<clinit>(InternalLoggerFactory.java:37)
	at io.netty.channel.MultithreadEventLoopGroup.<clinit>(MultithreadEventLoopGroup.java:34)
	at io.grpc.netty.Utils$DefaultEventLoopGroupResource.create(Utils.java:187)
	at io.grpc.netty.Utils$DefaultEventLoopGroupResource.create(Utils.java:171)
	at io.grpc.internal.SharedResourceHolder.getInternal(SharedResourceHolder.java:124)
	at io.grpc.internal.SharedResourceHolder.get(SharedResourceHolder.java:94)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:311)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:280)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:230)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:239)
	at com.google.api.gax.grpc.ServiceApiSettings$Builder$3.getOrBuildChannel(ServiceApiSettings.java:349)
	at com.google.cloud.logging.spi.v2.ConfigServiceV2Api.<init>(ConfigServiceV2Api.java:155)
	at com.google.cloud.logging.spi.v2.ConfigServiceV2Api.create(ConfigServiceV2Api.java:145)
	at com.google.cloud.logging.spi.DefaultLoggingRpc.<init>(DefaultLoggingRpc.java:140)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:68)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:62)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:491)
	at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:96)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:43)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:38)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:478)
	at com.google.cloud.logging.LoggingHandler.getLogging(LoggingHandler.java:276)
	at com.google.cloud.logging.LoggingHandler.write(LoggingHandler.java:351)
	at com.google.cloud.logging.LoggingHandler.flush(LoggingHandler.java:357)
	at com.google.cloud.logging.LoggingHandler.publish(LoggingHandler.java:292)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.info(Logger.java:1489)
	at com.google.cloud.runtimes.jetty9.StackDriverLogging.init(StackDriverLogging.java:37)
	at com.google.cloud.runtimes.jetty9.StackDriverLogging.main(StackDriverLogging.java:47)
Caused by: java.lang.NullPointerException
	at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:97)
	at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:90)
	at io.netty.util.concurrent.DefaultPromise.<clinit>(DefaultPromise.java:35)
	... 65 more
```

```
Exception in thread "main" java.lang.StackOverflowError
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:233)
	at sun.security.jca.ProviderList$ServiceList.tryGet(ProviderList.java:434)
	at sun.security.jca.ProviderList$ServiceList.access$200(ProviderList.java:376)
	at sun.security.jca.ProviderList$ServiceList$1.hasNext(ProviderList.java:486)
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1094)
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1176)
	at java.security.Signature.initSign(Signature.java:527)
	at com.google.api.client.util.SecurityUtils.sign(SecurityUtils.java:145)
	at com.google.api.client.json.webtoken.JsonWebSignature.signUsingRsaSha256(JsonWebSignature.java:637)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:208)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:97)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:74)
	at io.grpc.auth.ClientAuthInterceptor.getRequestMetadata(ClientAuthInterceptor.java:150)
	at io.grpc.auth.ClientAuthInterceptor.access$100(ClientAuthInterceptor.java:64)
	at io.grpc.auth.ClientAuthInterceptor$1.checkedStart(ClientAuthInterceptor.java:96)
	at io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:195)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:47)
	at com.google.api.gax.grpc.HeaderInterceptor$1.start(HeaderInterceptor.java:64)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:273)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:189)
	at com.google.api.gax.grpc.DirectCallable.futureCall(DirectCallable.java:58)
	at com.google.api.gax.grpc.ExceptionTransformingCallable.futureCall(ExceptionTransformingCallable.java:66)
	at com.google.api.gax.grpc.RetryingCallable$RetryingResultFuture.issueCall(RetryingCallable.java:222)
	at com.google.api.gax.grpc.RetryingCallable.futureCall(RetryingCallable.java:90)
	at com.google.api.gax.grpc.UnaryCallable.futureCall(UnaryCallable.java:242)
	at com.google.api.gax.grpc.UnaryCallable.futureCall(UnaryCallable.java:253)
	at com.google.cloud.logging.spi.DefaultLoggingRpc.write(DefaultLoggingRpc.java:199)
	at com.google.cloud.logging.LoggingImpl.writeAsync(LoggingImpl.java:503)
	at com.google.cloud.runtimes.jetty9.AsyncLoggingHandler.write(AsyncLoggingHandler.java:101)
	at com.google.cloud.runtimes.jetty9.LoggingHandler.flush(LoggingHandler.java:365)
	at com.google.cloud.runtimes.jetty9.LoggingHandler.publish(LoggingHandler.java:298)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.LoggingProxyImpl.log(LoggingProxyImpl.java:61)
	at sun.util.logging.LoggingSupport.log(LoggingSupport.java:120)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.doLog(PlatformLogger.java:610)
	at sun.util.logging.PlatformLogger.fine(PlatformLogger.java:364)
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:658)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1293)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:225)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:97)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:74)
	at io.grpc.auth.ClientAuthInterceptor.getRequestMetadata(ClientAuthInterceptor.java:150)
	at io.grpc.auth.ClientAuthInterceptor.access$100(ClientAuthInterceptor.java:64)
	at io.grpc.auth.ClientAuthInterceptor$1.checkedStart(ClientAuthInterceptor.java:96)
	at io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:195)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:47)
	at com.google.api.gax.grpc.HeaderInterceptor$1.start(HeaderInterceptor.java:64)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:273)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:189)
	at com.google.api.gax.grpc.DirectCallable.futureCall(DirectCallable.java:58)
	at com.google.api.gax.grpc.ExceptionTransformingCallable.futureCall(ExceptionTransformingCallable.java:66)

...

	at com.google.api.gax.grpc.RetryingCallable$RetryingResultFuture.issueCall(RetryingCallable.java:222)
	at com.google.api.gax.grpc.RetryingCallable.futureCall(RetryingCallable.java:90)
	at com.google.api.gax.grpc.UnaryCallable.futureCall(UnaryCallable.java:242)
	at com.google.api.gax.grpc.UnaryCallable.futureCall(UnaryCallable.java:253)
	at com.google.cloud.logging.spi.DefaultLoggingRpc.write(DefaultLoggingRpc.java:199)
	at com.google.cloud.logging.LoggingImpl.writeAsync(LoggingImpl.java:503)
	at com.google.cloud.runtimes.jetty9.AsyncLoggingHandler.write(AsyncLoggingHandler.java:101)
	at com.google.cloud.runtimes.jetty9.LoggingHandler.flush(LoggingHandler.java:365)
	at com.google.cloud.runtimes.jetty9.LoggingHandler.publish(LoggingHandler.java:298)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.LoggingProxyImpl.log(LoggingProxyImpl.java:61)
	at sun.util.logging.LoggingSupport.log(LoggingSupport.java:120)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.doLog(PlatformLogger.java:610)
	at sun.util.logging.PlatformLogger.fine(PlatformLogger.java:364)
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:658)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1293)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:225)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:97)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:74)
	at io.grpc.auth.ClientAuthInterceptor.getRequestMetadata(ClientAuthInterceptor.java:150)
	at io.grpc.auth.ClientAuthInterceptor.access$100(ClientAuthInterceptor.java:64)
	at io.grpc.auth.ClientAuthInterceptor$1.checkedStart(ClientAuthInterceptor.java:96)
	at io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:195)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:47)
	at com.google.api.gax.grpc.HeaderInterceptor$1.start(HeaderInterceptor.java:64)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:273)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:189)
	at com.google.api.gax.grpc.DirectCallable.futureCall(DirectCallable.java:58)
	at com.google.api.gax.grpc.ExceptionTransformingCallable.futureCall(ExceptionTransformingCallable.java:66)
	at com.google.api.gax.grpc.RetryingCallable$RetryingResultFuture.issueCall(RetryingCallable.java:222)
	at com.google.api.gax.grpc.RetryingCallable.futureCall(RetryingCallable.java:90)
	at com.google.api.gax.grpc.UnaryCallable.futureCall(UnaryCallable.java:242)
	at com.google.api.gax.grpc.UnaryCallable.futureCall(UnaryCallable.java:253)
	at com.google.cloud.logging.spi.DefaultLoggingRpc.write(DefaultLoggingRpc.java:199)
	at com.google.cloud.logging.LoggingImpl.writeAsync(LoggingImpl.java:503)
	at com.google.cloud.runtimes.jetty9.AsyncLoggingHandler.write(AsyncLoggingHandler.java:101)
	at com.google.cloud.runtimes.jetty9.LoggingHandler.flush(LoggingHandler.java:365)
	at com.google.cloud.runtimes.jetty9.LoggingHandler.publish(LoggingHandler.java:298)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.LoggingProxyImpl.log(LoggingProxyImpl.java:61)
	at sun.util.logging.LoggingSupport.log(LoggingSupport.java:120)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.doLog(PlatformLogger.java:610)
	at sun.util.logging.PlatformLogger.fine(PlatformLogger.java:364)
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:658)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1293)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:225)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:97)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:74)
	at io.grpc.auth.ClientAuthInterceptor.getRequestMetadata(ClientAuthInterceptor.java:150)
```

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**
Also:
* Reducing the scope of synchronized blocks
* Removing logger exclusions except for Http2FrameLogger

Fixes #1386

### CODE REVIEW

**Comment by gregw** [comment]
I testing this in https://github.com/GoogleCloudPlatform/jetty-runtime/tree/master-68-stackdriver and it works both locally and when deployed in the Flex environment.  I was able to deploy with full FINE logging.

**Comment by michaelbausor** [comment]
LGTM, let @pongad take a look also

File: google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java [hunk 1]
```diff
@@ -272,23 +244,55 @@ Formatter getFormatterProperty(String name, Formatter defaultValue) {
    */
   Logging getLogging() {
     if (logging == null) {
-      logging = options.getService();
+      synchronized (this) {
```
Comment (pongad) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java]: Is this change made so that `getLogging` can be called from multiple threads? If so, there's a subtle bug here. A way to fix it is to make `logging` `volatile`. See http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

File: google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java [hunk 2]
```diff
@@ -350,34 +354,59 @@ private static Severity severityFor(Level level) {
...
-      buffer.clear();
     }
   }
 
   /**
    * Closes the handler and the associated {@link Logging} object.
    */
   @Override
-  public synchronized void close() throws SecurityException {
+  public void close() throws SecurityException {
```
Comment (pongad) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java]: I think this is correct after the `volatile` fix but I'd prefer making this method `synchronized`. Closing probably happens infrequently, and double-checking is error-prone.

File: google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java [hunk 3]
```diff
@@ -272,23 +244,55 @@ Formatter getFormatterProperty(String name, Formatter defaultValue) {
...
+
+      List<LogEntry> flushBuffer = null;
+      WriteOption[] flushWriteOptions = null;
+
+      synchronized (this) {
+        if (entry != null) {
+          buffer.add(entry);
+        }
+        if (buffer.size() >= flushSize || record.getLevel().intValue() >= flushLevel.intValue()) {
+          flushBuffer = buffer;
```
Comment (pongad) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java]: Can't we just call `flush` here?

File: google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java (hunk 1 above)
Comment (garrettjonesgoogle) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java]: Well the `close()` method was synchronized already, and the only thing that `close()` protects is the `logging` variable, so it looked like the protection was incomplete to me. Thanks for catching the `volatile` issue, I will fix it.

File: google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java (hunk 3 above)
Comment (garrettjonesgoogle) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java]: I was trying to move the rpc call out of the `synchronized` block.

File: google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java (hunk 2 above)
Comment (pongad) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java]: I have one more concern. Is it the user's job to not call `close` concurrently with `publish`? Both methods might get the same logger and `logger.close` and `getLogging().write` can race. I'm not sure how Bundling handles this

Comment (garrettjonesgoogle) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java]: Hmm good point about closing being infrequent - making the method `synchronized` will be simpler.

Comment (garrettjonesgoogle) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java]: yeah, a user shouldn't call `close` concurrently with `publish`.

**Comment by garrettjonesgoogle** [comment]
PTAL

File: google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java (hunk 2 above)
Comment (pongad) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java]: sgtm
