### PR TITLE
BigQuery: Allow job to extract or load table across projects

### LINKED ISSUE #3924: ExtractJobConfiguration's setProjectId makes cross-project BQ extracts impossible
Hi! I was looking into migrating one of our projects from `google-api-services-bigquery` to `google-cloud-bigquery` & noticed a possible regression in the Extract job config in the client library. One of our integration tests extracts data from `bigquery-public-data:samples.shakespeare` into a GCS bucket in our own GCP project. However, after migrating, the test fails because the extract job can't find the BQ table `{OUR_GCP_PROJECT}:samples.shakespeare`.

some scala code replicating the issue:
```
val gcpProject = "some-gcp-project"
val bqClient: com.google.cloud.bigquery.BigQuery = ... // authenticated to $gcpProject

val sourceTableId = TableId.of("bigquery-public-data", "samples", "shakespeare")
val destGcsUri = s"gs://$gcpProject/it/${UUID.randomUUID}"

val config = ExtractJobConfiguration
    .newBuilder(sourceTableId, destGcsUri)
    .setFormat("AVRO")

val jobInfo = JobInfo.newBuilder(config.build()).build()
print(jobInfo)

val job = bqClient.create(jobInfo).waitFor()
print(job.getStatus.getError)
```

this prints

`JobInfo{job=null, status=null, statistics=null, userEmail=null, etag=null, generatedId=null, selfLink=null, configuration=ExtractJobConfiguration{type=EXTRACT, sourceTable={datasetId=samples, projectId=bigquery-public-data, tableId=shakespeare}, destinationUris=[gs://some-gcp-project/it/9270d23f-de63-41e8-a56a-e7c140297e38], format=AVRO, printHeader=null, fieldDelimiter=null, compression=null}}`

and

 `BigQueryError{reason=notFound, location=null, message=Not found: Table some-gcp-project:samples.shakespeare was not found in location US}[info]`.

I think the reason is because `ExtractJobConfiguration` [overrides `setProjectId`](https://github.com/googleapis/google-cloud-java/blob/675ace7601e2c09474ce986d5d2223af5cb15f28/google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExtractJobConfiguration.java#L237) to apply the credentialed `projectId` param specifically to the source table, overriding what it was originally set to.

wdyt? Am I just mis-using the new API?

thanks!

### PR DESCRIPTION
**Pull request by ajaaym**
Fixes #3924 ExtractJobConfiguration's setProjectId makes cross-project BQ extracts impossible

### CODE REVIEW

File: google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/CopyJobConfigurationTest.java [hunk 1]
```diff
@@ -115,10 +118,33 @@ public void testToPbAndFromPb() {
 
   @Test
   public void testSetProjectId() {
-    CopyJobConfiguration configuration = COPY_JOB_CONFIGURATION_MULTIPLE_TABLES.setProjectId("p");
-    assertEquals("p", configuration.getDestinationTable().getProject());
+    CopyJobConfiguration configuration = COPY_JOB_CONFIGURATION_MULTIPLE_TABLES.setProjectId(TEST_PROJECT_ID);
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/CopyJobConfigurationTest.java]: From the code formatter:

```suggestion
    CopyJobConfiguration configuration =
        COPY_JOB_CONFIGURATION_MULTIPLE_TABLES.setProjectId(TEST_PROJECT_ID);
```

**Comment by chingor13** [comment]
The integration test failure is a quote issue on logging.

**Comment by sduskis** [comment]
@ajaaym can you please fix the failed formatting test?

**Comment by ajaaym** [comment]
@sduskis done
