### PR TITLE
Storage : Fix manage resumeable signedURL uploads.

### LINKED ISSUE #2462: Storage service should manage resumeable signedURL uploads
google-cloud-java currently allows users to mint a signedURL but offers not way to separately manage the resumable upload given _just_ the signedURL.

The usecase for this is if i have in possession a signedURL that allows for resumeable uploads, i'd like to use google-cloud-java to manage the transfer for me. 

some background:

 - a resumable transfer session requires a special header to get it going (```x-goog-resumable: start```) as described [here](https://cloud.google.com/storage/docs/xml-api/resumable-upload#step_1wzxhzdk14initiate_the_resumable_upload).   At the moment, our java libraries do not support baking in the canonical headers into the signedURL.  see [issue#2000](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2000)
          
- Even if we do support a signeURL that allows for the transfer initiation, i didn't see anyplace within the library which will manage that transfer for you (i.,e handle retries, partial transfers, etc) given just a signedURL.  It does appear that resumeable uploads are [supported](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java#L834)  but that appears to be about authenticated uploads (not signedURL)

my 2c on how this may look

create a signedURL somewhere else and provide a header to allow the uploads 

```java
         Storage storage_service = StorageOptions.newBuilder()
        .setCredentials(ServiceAccountCredentials.fromStream(new FileInputStream("svc_acct.json")))
        .build()
        .getService();          
        
        BlobId blobId = BlobId.of(bucketName, objectName);
        BlobInfo blobInfo = BlobInfo.newBuilder(blobId).setContentType(content_type).build();
    
        SignUrlOption opts = SignUrlOption.withContentType()  // (+new way to add headers:("x-goog-resumable:start")       
        URL signedUrl = storage_service.signUrl(blobInfo, 60,  TimeUnit.SECONDS, opts);

```

then on the client, google-cloud-java would upload an object without needed authentication...and manage the retry on resume.

```java
        Storage storage_service_no_creds = StorageOptions.newBuilder()
        .setCredentials(NoCredentials.getInstance())
        .build()
        .getService();         
       
        storage_service_no_creds.create(blobInfo, "filecontent".getBytes(UTF_8), signedUrl);      

```

### PR DESCRIPTION
**Pull request by abhinav-qlogic**
Fixes #2462

### CODE REVIEW

**Comment by ajaaym** [comment]
@frankyn can you please review?

File: google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java [hunk 1]
```diff
@@ -83,6 +92,26 @@ public String call() {
     }
   }
 
+  private static String open(final URL signURL, final StorageOptions options) {
+    try {
+      return runWithRetries(
+          new Callable<String>() {
+            @Override
+            public String call() {
+              if (!signURL.getQuery().contains("&Signature=")) {
```
Comment (JesseLovelace) [inline google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java]: Is this a sufficient check for signature validity? Why not check for other fields as well?

File: google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java [hunk 2]
```diff
@@ -34,10 +35,18 @@
     this(options, blob, open(options, blob, optionsMap));
   }
 
+  BlobWriteChannel(StorageOptions options, URL signURL) {
```
Comment (JesseLovelace) [inline google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java]: Wouldn't signedURL be a more appropriate name that signURL?

File: google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java [hunk 3]
```diff
@@ -822,6 +822,39 @@ public String open(StorageObject object, Map<Option, ?> options) {
...
+      GenericUrl url = new GenericUrl(signURL);
+      url.set("uploadType", "resumable");
+      String bytesArrayParameters = "";
+      byte[] bytesArray = new byte[bytesArrayParameters.length()];
+      HttpRequestFactory requestFactory = storage.getRequestFactory();
+      HttpRequest httpRequest =
+          requestFactory.buildPostRequest(
+              url, new ByteArrayContent("", bytesArray, 0, bytesArray.length));
+      HttpHeaders requestHeaders = httpRequest.getHeaders();
+      requestHeaders.set("X-Upload-Content-Type", firstNonNull("", "application/octet-stream"));
```
Comment (JesseLovelace) [inline google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: Why the firstNonNull where the first parameter is an empty string?

File: google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java [hunk 4]
```diff
@@ -83,6 +92,29 @@ public String call() {
...
   }
 
+  private static String open(final URL signedURL, final StorageOptions options) {
+    try {
+      return runWithRetries(
+          new Callable<String>() {
+            @Override
+            public String call() {
+              String signedURLQuery = signedURL.getQuery();
+              if (!signedURLQuery.startsWith("GoogleAccessId=")
```
Comment (JesseLovelace) [inline google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java]: This wouldn't be compatible with V4 Signing (which will become default in the future), which starts with X-Goog-Algorithm instead of GoogleAccessId. See https://github.com/googleapis/google-cloud-java/pull/4692

Comment (abhinav-qlogic) [reply google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobWriteChannel.java]: @JesseLovelace V4 Signing support changes Done

File: google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java [hunk 5]
```diff
@@ -2068,6 +2068,13 @@ Blob create(
    */
   WriteChannel writer(BlobInfo blobInfo, BlobWriteOption... options);
 
+  /**
+   * accept signURL and return a channel for writing content.
```
Comment (JesseLovelace) [inline google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java]: Can you make this more consistent with the other documentation in this class? i.e. present tense ("Accepts" instead of "accept") and provide an example?

File: google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java (hunk 3 above)
Comment (abhinav-qlogic) [reply google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java]: @JesseLovelace  changes done with example.

File: google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java (hunk 5 above)
Comment (abhinav-qlogic) [reply google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java]: @JesseLovelace changes done with example

File: google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java [hunk 6]
```diff
@@ -289,6 +289,13 @@ StorageObject compose(
    */
   String open(StorageObject object, Map<Option, ?> options);
 
+  /**
+   * Opens a resumable upload channel for a given signUrl.
+   *
+   * @throws StorageException upon failure
+   */
+  String open(String signURL);
```
Comment (JesseLovelace) [inline google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java]: Should be signedUrl

Comment (abhinav-qlogic) [reply google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java]: @JesseLovelace Changes Done.
