### PR TITLE
BigQuery: Fix support standard java date in QueryParameterValue classToType

### LINKED ISSUE #3589: com.google.cloud.bigquery.QueryParameterValue classToType should support standard Java date/time classes.
Please consider adding standard java date, datetime and time classes to the classToType method so that they can be used with "of" generic:
  /** Creates a {@code QueryParameterValue} object with the given value and type. */
  public static <T> QueryParameterValue of(T value, Class<T> type) {
    return of(value, classToType(type));
  }

### PR DESCRIPTION
**Pull request by pmakani**
Fixes #3589 com.google.cloud.bigquery.QueryParameterValue classToType should support standard Java

### CODE REVIEW

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java [hunk 1]
```diff
@@ -67,6 +70,7 @@
       DateTimeFormatter.ofPattern("HH:mm:ss.SSSSSS");
   private static final DateTimeFormatter datetimeFormatter =
       DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSSSSS");
+  private static final DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
```
Comment (sduskis) [inline google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java]: Please use `DateTimeFormatter` instead of the java standard format.

Comment (pmakani) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java]: DateTimeFormatter is only available after java 8.

Comment (sduskis) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java]: Please see line 72.

Comment (pmakani) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java]: Updated to remove formatter and replaced with utility method from google cloud date. Sorry I misread your comment earlier and though of jdk8s datetimeformatter.
