### PR TITLE
Make DNS batch get zone/changerequest return null for NOT_FOUND

### LINKED ISSUE #949: DNS batch getZone do not return null for NOT FOUND
Although documented [here](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-dns/src/main/java/com/google/cloud/dns/DnsBatch.java#L116) 404 (NOT FOUND) exceptions are not translated into `null` (should be done [here](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-dns/src/main/java/com/google/cloud/dns/DnsBatch.java#L271)).

### PR DESCRIPTION
**Pull request by mziccard**
This fixes #949: `DnsBatch.getZone` and `DnsBatch.getChangeRequest` now return `null` for `NOT_FOUND`. This PR also adds more tests.

### CODE REVIEW

File: gcloud-java-dns/src/main/java/com/google/cloud/dns/DnsBatch.java [hunk 1]
```diff
@@ -337,17 +343,29 @@ public void onFailure(GoogleJsonError googleJsonError) {
...
+            response));
       }
 
       @Override
       public void onFailure(GoogleJsonError googleJsonError) {
-        result.error(new DnsException(googleJsonError, idempotent));
+        DnsException serviceException = new DnsException(googleJsonError, idempotent);
+        if (nullForNotFound && serviceException.code() == HTTP_NOT_FOUND) {
+          if ("entity.parameters.changeId".equals(serviceException.location())
+              || (serviceException.getMessage() != null
```
Comment (mziccard) [inline gcloud-java-dns/src/main/java/com/google/cloud/dns/DnsBatch.java]: Codacy Issue found: [Useless parentheses.](https://www.codacy.com/app/mziccard/gcloud-java/file/2448645437/issues/source?bid=3123103&fileBranchId=3247517#l360)

File: gcloud-java-dns/src/main/java/com/google/cloud/dns/DnsBatch.java [hunk 2]
```diff
@@ -337,17 +343,29 @@ public void onFailure(GoogleJsonError googleJsonError) {
...
+        result.success(response == null ? null : ChangeRequest.fromPb(options.service(), zoneName,
+            response));
       }
 
       @Override
       public void onFailure(GoogleJsonError googleJsonError) {
-        result.error(new DnsException(googleJsonError, idempotent));
+        DnsException serviceException = new DnsException(googleJsonError, idempotent);
+        if (nullForNotFound && serviceException.code() == HTTP_NOT_FOUND) {
+          if ("entity.parameters.changeId".equals(serviceException.location())
```
Comment (mziccard) [inline gcloud-java-dns/src/main/java/com/google/cloud/dns/DnsBatch.java]: Codacy Issue found: [These nested if statements could be combined](https://www.codacy.com/app/mziccard/gcloud-java/file/2448645437/issues/source?bid=3123103&fileBranchId=3247517#l359)

File: gcloud-java-dns/src/main/java/com/google/cloud/dns/spi/DefaultDnsRpc.java [hunk 3]
```diff
@@ -331,15 +331,14 @@ public Change getChangeRequest(String zoneName, String changeRequestId, Map<Opti
...
       DnsException serviceException = translate(ex, true);
-      if (serviceException.code() == HTTP_NOT_FOUND) {
-        if ("entity.parameters.changeId".equals(serviceException.location())
-            || (serviceException.getMessage() != null
-            && serviceException.getMessage().contains("parameters.changeId"))) {
-          // the change id was not found, but the zone exists
-          return null;
-        }
-        // the zone does not exist, so throw an exception
+      if (serviceException.code() == HTTP_NOT_FOUND
```
Comment (aozarov) [inline gcloud-java-dns/src/main/java/com/google/cloud/dns/spi/DefaultDnsRpc.java]: Honestly, I am not sure if that makes the code more readable in this case.
Fine as is if you think otherwise.

File: gcloud-java-dns/src/main/java/com/google/cloud/dns/DnsBatch.java [hunk 4]
```diff
@@ -203,14 +203,15 @@ DnsOptions options() {
   public DnsBatchResult<ChangeRequest> applyChangeRequest(String zoneName,
       ChangeRequestInfo changeRequest, Dns.ChangeRequestOption... options) {
     DnsBatchResult<ChangeRequest> result = new DnsBatchResult<>();
-    RpcBatch.Callback<Change> callback = createChangeRequestCallback(zoneName, result, false);
+    RpcBatch.Callback<Change> callback =
```
Comment (aozarov) [inline gcloud-java-dns/src/main/java/com/google/cloud/dns/DnsBatch.java]: Shall we fix the javadoc? returning {@code null} in this case does not apply.

Comment (mziccard) [inline gcloud-java-dns/src/main/java/com/google/cloud/dns/DnsBatch.java]: Good catch! I didn't notice

**Comment by aozarov** [comment]
LGTM
