### PR TITLE
ci(generation): skip files inheriting coordinates in release check

### LINKED ISSUE #12840: existing-versions-check failed in release PR
existing-versions-check failed in 1.85.0 release PR due to the following errors:
```
Checking :google-auth-library-appengine::Couldn't parse the pom file: ./google-auth-library-java/appengine/pom.xml
```

See [error log](https://github.com/googleapis/google-cloud-java/actions/runs/24373536681/job/71182069776) for details

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes #12840

### CODE REVIEW

File: generation/check_existing_release_versions.sh [hunk 1]
```diff
@@ -18,10 +18,14 @@ function find_existing_version_pom() {
...
       "${pom_file}")
   echo -n "Checking ${group_id}:${artifact_id}:${version}:"
-  if [ -z "${group_id}" ] || [ -z "${artifact_id}" ] || [ -z "${version}" ]; then
-    echo "Couldn't parse the pom file: $pom_file"
+  if [ -z "${artifact_id}" ]; then
+    echo "Couldn't parse artifact_id in the pom file: $pom_file"
     exit 1
   fi
+  if [ -z "${group_id}" ] || [ -z "${version}" ]; then
+    echo "Skipping file without explicit coordinates (likely inherits): $pom_file"
```
Comment (suztomo) [inline generation/check_existing_release_versions.sh:26]: This will skip the case where group ID is inherited and version is wrong.

**Review by suztomo — APPROVED** [review]
> This will skip the case where group ID is inherited and version is wrong.

This is a corner case not worth implementing artifact inheritance resolution.

**Review by blakeli0 — APPROVED** [review]
