### PR TITLE
[Bigtable] GCRules.GCRule Javadoc fix for createTable

### LINKED ISSUE #4056: Bigtable: document that GCRules are only applied during compaction

### LINKED ISSUE #4090: Bigtable: update create table docs to demonstrate GCRules usage
Due to naming similarity of the corresponding proto class it's easy to mistakenly use proto classes 
Example of confusion:
https://gist.github.com/emmmile/2ffc8e390c05ecb40421e285de54f504

### PR DESCRIPTION
**Pull request by rahulKQL**
Fixes #4056 and FIxes #4090 (Both of these issues are related to GCRule).

- Have added a sample code for GCRule in BigtableTableAdminClient's createTable() & createTableAsync().
- Have added one line note about GCRule execution.

### CODE REVIEW

**Comment by rahulKQL** [comment]
@igorbernstein2 Please have a look. 

Q: Should we consider to adding [this note](https://github.com/googleapis/googleapis/blob/master/google/bigtable/admin/v2/table.proto#L127-L129) in client Javadoc as well?

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 1]
```diff
@@ -177,9 +177,13 @@ public void close() {
...
    *
    * <pre>{@code
+   * GCRules.GCRule rule = GCRules.GCRULES.union()
+   *     .rule(GCRules.GCRULES.maxAge(Duration.ofSeconds(1)))
+   *     .rule(GCRules.GCRULES.maxVersions(1));
+   *
    * Table table = client.createTable(
    *   CreateTableRequest.of("my-table")
-   *     .addFamily("cf2", GCRULES.maxVersions(1)
+   *     .addFamily("cf2", rule
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: please fix formatting

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 2]
```diff
@@ -177,9 +177,13 @@ public void close() {
    * <p>Sample code:
    *
    * <pre>{@code
+   * GCRules.GCRule rule = GCRules.GCRULES.union()
+   *     .rule(GCRules.GCRULES.maxAge(Duration.ofSeconds(1)))
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: Please use a more realistic example. Maybe maxVersions=1 & maxAge=1 month

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 3]
```diff
@@ -196,9 +200,13 @@ public Table createTable(CreateTableRequest request) {
    * <p>Sample code:
    *
    * <pre>{@code
+   * GCRules.GCRule rule = GCRules.GCRULES.intersection()
+   *     .rule(GCRules.GCRULES.maxAge(1, TimeUnit.SECONDS))
+   *     .rule(GCRules.GCRULES.maxVersions(1)
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: Please use a more realistic example

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java [hunk 4]
```diff
@@ -73,6 +73,8 @@ public CreateTableRequest addFamily(String familyId) {
    *
    * @param familyId
    * @param gcRule
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java]: Can you remove the empty params?

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/GCRules.java [hunk 5]
```diff
@@ -30,7 +30,11 @@
 
 // TODO(igorbernstein2): the distinction between GcRule & GCRule is too subtle, use fully qualified
 // names for the protos.
-/** Wraps {@link GcRule} protocol buffer object and exposes a simpler Fluent DSL model */
+/**
+ * Wraps {@link GcRule} protocol buffer object and exposes a simpler Fluent DSL model
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/GCRules.java]: s/exposes a simpler Fluent DSL model/and exposes a friendly api.

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/GCRules.java [hunk 6]
```diff
@@ -30,7 +30,11 @@
...
+ *
+ * <p>Note: GCRule are only applied when compaction starts for the table.
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/GCRules.java]: Note: Garbage collection executes opportunistically in the background, and
so it's possible for reads to return a cell even if it matches the active
GC expression for its family.  Please use appropriate filters in your reads to exclude
cells which are eligible for garbage collection

**Comment by rahulKQL** [comment]
@igorbernstein2
I have addressed feedback comments, Please have a fresh look.

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java [hunk 7]
```diff
@@ -103,13 +87,13 @@ public boolean equals(Object o) {
       return false;
     }
     CreateTableRequest that = (CreateTableRequest) o;
-    return Objects.equal(createTableRequest, that.createTableRequest)
+    return Objects.equal(requestBuilder, that.requestBuilder)
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java]: This is unrelated to this PR, but this looks broken. I don't think proto builders implement value equality checks. In a separate PR, can you add a unit test for equality and if its broken, fix it, by comparing requestBuilder.build() to that.requestBuilder.build(). Or something more clever

Comment (rahulKQL) [reply google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateTableRequest.java]: Have created #5079 to address fix.

**Comment by rahulKQL** [comment]
@sduskis @igorbernstein2 
I have rebased this PR with the latest master. Please have a look.

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 8]
```diff
@@ -177,9 +177,14 @@ public void close() {
    * <p>Sample code:
    *
    * <pre>{@code
+   * GCRules.GCRule removeAnyMatched = GCRULES
+   *   .union()
```
[the remark this answers is not in the document]
Comment (igorbernstein2) [reply google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: Also, it's a bit confusing that the docs for CreateTable start with a complex GCRule. Maybe split it up into 2 examples:

```java
// A table with a single column family, which retains only the latest value
Table table = client.createTable(
   CreateTableRequest.of("my-table")
     .addFamily("cf2", GCRULES.maxVersions(1))
);

// Another table with more complex garbage collection rules
Table table = client.createTable(
   CreateTableRequest.of("my-table")
     .addFamily("cf2", GCRULES.union()
        .rule(...)
        .rule(...)
);

```

[the remark this answers is not in the document]
Comment (igorbernstein2) [reply google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: Also, please add a `@see` annotation for GCRULES

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 9]
```diff
@@ -177,13 +178,24 @@ public void close() {
    * <p>Sample code:
    *
    * <pre>{@code
+   * // A table with a single column family, which retains only the latest value.
    * Table table = client.createTable(
    *   CreateTableRequest.of("my-table")
-   *     .addFamily("cf2", GCRULES.maxVersions(1)
+   *     .addFamily("cf2", GCRULES.maxVersions(1))
+   * );
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: There seems to be an extra closing paren

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 10]
```diff
@@ -177,13 +178,24 @@ public void close() {
...
+   *
+   * // Another table with more complex garbage collection rules.
+   * Table table = client.createTable(
+   *   CreateTableRequest.of("my-table")
+   *     .addFamily("cf2", GCRULES.union()
+   *       .rule(GCRULES.maxAge(Duration.ofDays(30)))
+   *       .rule(GCRULES.maxVersions(5))
+   *     )
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: extra closing parent

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 11]
```diff
@@ -177,13 +178,24 @@ public void close() {
...
    * );
    * }</pre>
    *
    * @see CreateTableRequest for available options.
+   * @see GCRules#GCRULES for available options.
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: @see GCRules for a documentation on available garbage collection rules

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 12]
```diff
@@ -196,9 +208,19 @@ public Table createTable(CreateTableRequest request) {
    * <p>Sample code:
    *
    * <pre>{@code
+   * // A table with a single column family, which retains values up to 7 days.
    * ApiFuture<Table> tableFuture = client.createTableAsync(
    *   CreateTableRequest.of("my-table")
-   *     .addFamily("cf", GCRules.GCRULES.maxVersions(1))
+   *     .addFamily("cf", GCRULES.maxAge(Duration.ofDays(7)))
+   * );
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: extra paren

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 13]
```diff
@@ -196,9 +208,19 @@ public Table createTable(CreateTableRequest request) {
...
+   *
+   * // Another table with more complex garbage collection rules.
+   * ApiFuture<Table> tableFuture = client.createTableAsync(
+   *   CreateTableRequest.of("my-table")
+   *     .addFamily("cf", GCRULES.intersection()
+   *       .rule(GCRULES.maxAge(120, TimeUnit.HOURS))
+   *       .rule(GCRULES.maxVersions(10))
+   *     )
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: extra paren

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java [hunk 14]
```diff
@@ -217,6 +239,7 @@ public Table createTable(CreateTableRequest request) {
    * }</pre>
    *
    * @see CreateTableRequest for available options.
+   * @see GCRules#GCRULES for available options.
```
Comment (igorbernstein2) [inline google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: see above for a slightly better wording

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java (hunk 9 above)
Comment (rahulKQL) [reply google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: This parenthesis is to close the createTable, Please advise me if this needs to be inlined with `#addFamily`

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java (hunk 10 above)
Comment (rahulKQL) [reply google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: I added this parenthesis for addFamily(as this has a multi-line argument).

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java (hunk 13 above)
Comment (rahulKQL) [reply google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: I followed the similar pattern present in the file, _To close paran inline if arguments are inlined. In the case of multiline arguments, close the operation in the new line._
Please let me know if I should reformat this sample code.

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java (hunk 10 above)
Comment (igorbernstein2) [reply google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: my mistake

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java (hunk 9 above)
Comment (igorbernstein2) [reply google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: my mistake

File: google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java (hunk 13 above)
Comment (igorbernstein2) [reply google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java]: nope, my mistake
