### PR TITLE
fix(logging): add ability to filter MDC labels

### LINKED ISSUE #6320: Add possibility to control MDC values for adding to log message
### The issue:
All values from MDC are written as labels to each log message, even if there is no need in some of them.
Usually MDC is populated by a built-in components (like MDCInsertingServletFilter) with all possible values, but only several of them are used in log message.

```
google-cloud-java/google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java

    for (Map.Entry<String, String> entry : e.getMDCPropertyMap().entrySet()) {
      if (null != entry.getKey() && null != entry.getValue()) {
        builder.addLabel(entry.getKey(), entry.getValue());
      }
    }
```

### Possible solution:
1. Add possibility to control which MDC values should be added to log message.
2. Add Enhancer to add required values of MDC.

### PR DESCRIPTION
**Pull request by codyoss**
Currently all MDC values are being written as labels in a LogEntry.
This is not desirable for everyone. By adding MDCEventEnhancer a user
now has the ability to easily filter which MDC entries get converted
into labels. To maintain backwards compatability the default
implementation is to write all entries as labels. If a user wants to
filter these, they just need to extend MDCEventEnhancer, override the
filtering, and add the new classpath to their logback.xml.

Fixes #6320

### CODE REVIEW

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+import java.util.Map;
+
+/**
+ * MDCEventEnhancer takes values found in the MDC property map and adds them as labels to the {@link
+ * LogEntry}. This {@link LoggingEventEnhancer} is turned on by default. If you wish to filter which
+ * MDC values get added as labels to your {@link LogEntry}, extend this class and override {@link
+ * MDCEventEnhancer#labelFilter(Map.Entry)} accordingly. The default behavior is to add all entries
+ * as labels.
+ */
+public class MDCEventEnhancer implements LoggingEventEnhancer {
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java]: Do you think it's worthwhile to maintain this extra surface area moving forward? It seems like the `LoggingEventEnhancer` interface is simple enough for someone to implement a filtered label enhancer. The user now extends a base class and overrides one method vs. implementing one interface method (which looks like it's a functional interface to begin with).

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+  }
+
+  @Before
+  public void setUp() {
+    logging = EasyMock.createStrictMock(Logging.class);
+    loggingAppender = new TestLoggingAppender();
+  }
+
+  @Test
+  public void testDefaultMDCEventEnhancer() {
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java]: I would probably leave this test in the `AppenderTest` as we're testing the appender's default behavior. If you want to test the MDCEventEnhancer directly, I'd put that test here.

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+    MDC.remove("mdc3");
+    Map<String, String> capturedArgumentMap =
+        capturedArgument.getValue().iterator().next().getLabels();
+    assertThat(capturedArgumentMap.get("mdc1")).isEqualTo("value1");
+    assertThat(capturedArgumentMap.get("mdc2")).isNull();
+    assertThat(capturedArgumentMap.get("mdc3")).isEqualTo("value3");
+  }
+
+  @Test
+  public void testCustomMDCEventEnhancer() {
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java]: Rather than implementing a custom event enhancer, and testing its e2e behavior, I might test that the appender can configure one or more custom enhancers that we verify are called.

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java (hunk 1 above)
Comment (codyoss) [reply google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java]: I think so. Only because if we don't expose this as a `LoggingEventEnhancer` I can't think of a good way to give users a hook into this without breaking behavior and removing automatically adding values as labels. If we are okay with changing that behavior, that is for sure another option.

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java (hunk 2 above)
Comment (codyoss) [reply google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java]: That is fair

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java (hunk 1 above)
Comment (chingor13) [reply google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java]: We could still have this class as a non-public implementation detail of that continues to implement the default behavior. By maintaining additional surface area, I mean encouraging people to extend this class vs. writing their own custom `LoggingEventEnhancer` implementation from scratch.

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java (hunk 3 above)
Comment (codyoss) [reply google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java]: okay

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java (hunk 1 above)
Comment (codyoss) [reply google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java]: Ah, gottcha. I like that, good idea.

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/FilteredMVCEventEnhancer.java [hunk 4]
```diff
@@ -0,0 +1,26 @@
+/*
+ * Copyright 2017 Google LLC
```
Comment (BenWhitehead) [inline google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/FilteredMVCEventEnhancer.java]: `s/2017/2019/g`

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java [hunk 5]
```diff
@@ -0,0 +1,121 @@
+/*
+ * Copyright 2017 Google LLC
```
Comment (BenWhitehead) [inline google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java]: `s/2017/2019/g`

**Comment by codyoss** [comment]
> I thought of a possible behavior breaking change: if a user already added an additional `LoggingEventEnhancer`, they would now lose the default label setting behavior.

@chingor13 That is a good point. I did document this behavior on the class, but I suppose it is technically breaking. Short of exposing a custom hook that only relates specifically to MDCs I don't know a good way around this. I am open to suggestions.

**Comment by codyoss** [comment]
What is our compatibility promise for artifacts labeled alpha? The version here is `0.111.1-alpha-SNAPSHOT`.

**Comment by chingor13** [comment]
We can break the behavior, but we definitely need to document it in the release notes.

**Comment by codyoss** [comment]
I vote we take the breaking behavior and document it in the release notes. I think this implementation will offer more flexibility for the users as the library. Using `LoggingEventEnhancer ` is not well documented in our examples today so I anticipate little breakage. The commit that introduced this MDC feature fbb4776 was not from too far back.

File: google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+import java.util.Collections;
+import org.junit.Before;
+import org.junit.Test;
+
+public class MDCEventEnhancerTest {
+  private MDCEventEnhancer classUnderTest;
+
+  @Before
+  public void setUp() {
+    classUnderTest = new MDCEventEnhancer();
```
Comment (elharo) [inline google-cloud-clients/google-cloud-contrib/google-cloud-logging-logback/src/test/java/com/google/cloud/logging/logback/MDCEventEnhancerTest.java]: could just initialize the field. That lets it be final and makes this simpler.

**Comment by elharo** [comment]
The alpha status is wonky. Some artifacts are alpha, some are beta, and some are GA.

**Comment by codyoss** [comment]
@chingor13 Thoughts on this change?

**Comment by codyoss** [comment]
I am going to merge this. Once done I will cherry-pick these changes to goolgeapis/java-logging

**Comment by gendolf3d** [comment]
Hello! I'm just curious when it's being planned to merge fix to  `goolgeapis/java-logging` project?
Thank you in advance!
