### PR TITLE
Put new retry options in CloudStorageConfiguration

### LINKED ISSUE #3868: google-cloud-nio: implement configurable retries/reopens
google-cloud-nio currently will retry and even reopen channels on a number of conditions (if turned on in configuration). It would be nice to be able to specify which exceptions to reopen for, and which HTTP codes to retry on (in addition to the codes that already have `.isRetriable()` return true).

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
Add `retriableHttpCodes` and `reopenableExceptions` so the user can, if they choose, customize the conditions under which we retry an access or reopen a channel after an exception closed it.

This can be handy if a cloud provider starts transiently throwing exceptions that would normally indicate a fatal condition, but which in practice will pass if retried.

The backoff logic in retries / reopens in unmodified.

Also update `testListFilesInRootDirectory` to reflect the new reality that `Files.newDirectoryStream` correctly returns absolute or relative paths depending on its input (as of #3773).

Fixes #3868

### CODE REVIEW

**Comment by jean-philippe-martin** [comment]
Rebased to catch up with latest changes to master.

**Comment by jean-philippe-martin** [comment]
Rebased again to catch up with the latest changes in master.

**Comment by jean-philippe-martin** [comment]
Github's saying again that we're out-of-date with master, but I'll let this as-is until after the review, so the code is stable for someone to review.

**Comment by jean-philippe-martin** [comment]
That integration test failure was with Spanner, which seems unrelated to this change. Is there a way to rerun the checks?

File: google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java [hunk 1]
```diff
@@ -34,26 +30,30 @@
   private long totalWaitTime; // in milliseconds
   private final int maxRetries;
   private final int maxReopens;
+  private final CloudStorageConfiguration config;
 
   /**
    * Create a CloudStorageRetryHandler with the maximum retries and reopens set to the same value.
    *
-   * @param maxRetriesAndReopens value for both maxRetries and maxReopens
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: This change looks like a breaking API change. Is this intentional?

We can add the new constructor, deprecate this one and then remote the deprecated one later?

Comment (jean-philippe-martin) [reply google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: You're right, this is a public method so it's part of the API (even though I don't know of anyone using this class directly). I've added the old one back as you suggested, marked as deprecated.

File: google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java [hunk 2]
```diff
@@ -34,26 +30,45 @@
...
+    this.config = CloudStorageConfiguration.DEFAULT;
+  }
 
   /**
    * Create a CloudStorageRetryHandler with the maximum retries and reopens set to the same value.
    *
-   * @param maxRetriesAndReopens value for both maxRetries and maxReopens
+   * @param config - configuration for reopens and retryable codes.
    */
-  public CloudStorageRetryHandler(final int maxRetriesAndReopens) {
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: We're still removing this constructor with a single int used for both retries and reopens.

Comment (chingor13) [reply google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: We should put this one back and also mark it as deprecated.

Comment (jean-philippe-martin) [reply google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: Oh you're right, thank you for catching that! I put it back, deprecated.

File: google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java [hunk 3]
```diff
@@ -34,26 +30,60 @@
...
+  }
+
+  /**
+   * Create a CloudStorageRetryHandler with the maximum retries and reopens set to different values.
+   *
+   * @param maxRetries maximum number of retries
+   * @param maxReopens maximum number of reopens
+   * @param config http codes we'll retry on, and exceptions we'll reopen on.
+   */
+  public CloudStorageRetryHandler(final int maxRetries, final int maxReopens, final CloudStorageConfiguration config) {
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: Do we need this one if you can set the maxRetries and maxReopens from the config?

Comment (jean-philippe-martin) [reply google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: We need this one because the config only holds maxReopens, not maxRetries. The maxReopen option there lets us override the setting in the config.

Comment (chingor13) [reply google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: Ah, I missed that. Does it make sense to add that configuration option to the CloudStorageConfiguration?

File: google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java [hunk 4]
```diff
@@ -34,26 +30,62 @@
...
+
 
   /**
    * Create a CloudStorageRetryHandler with the maximum retries and reopens set to the same value.
    *
    * @param maxRetriesAndReopens value for both maxRetries and maxReopens
+   *
+   * @deprecated use CloudStorageRetryHandler(CloudStorageConfiguration) instead.
    */
+  @java.lang.Deprecated
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: Import this?

File: google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java [hunk 5]
```diff
@@ -34,26 +30,62 @@
...
-  /**
+    /**
    * Create a CloudStorageRetryHandler with the maximum retries and reopens set to different values.
    *
    * @param maxRetries maximum number of retries
    * @param maxReopens maximum number of reopens
+   *
+   * @deprecated use CloudStorageRetryHandler(CloudStorageConfiguration) instead.
    */
+  @java.lang.Deprecated
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: Ditto, import this?

File: google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java [hunk 6]
```diff
@@ -34,26 +30,62 @@
...
   public CloudStorageRetryHandler(final int maxRetriesAndReopens) {
     this.maxRetries = maxRetriesAndReopens;
     this.maxReopens = maxRetriesAndReopens;
+    // we're just using the retry parameters from the config, so it's OK to have a default.
+    this.config = CloudStorageConfiguration.DEFAULT;
   }
 
-  /**
+    /**
```
Comment (chingor13) [inline google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: nit: extra indentation

File: google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java (hunk 3 above)
Comment (jean-philippe-martin) [reply google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageRetryHandler.java]: That would make for a much bigger change than we were aiming for here. The reopen can be specified each time we open a connection (in the public API), so we'd have to createa a new config object just to carry this parameter to the retry handler.
