### PR TITLE
Bigquery: Fix bug for sourceFormat Bigtable ExternalTableDefinition.

### LINKED ISSUE #6417: Querying Cloud Bigtable data
I am trying to follow these steps to query Bigtable data using a permanent table:
https://cloud.google.com/bigquery/external-data-bigtable#permanent-tables

The approach works quite well using the CLI, but I now have to implement it as part of our Java service.
Essentially, this is what I want to accomplish:
```
  public Table createExternalTable(
      String datasetName,
      String tableName,
      String sourceFormat,
      String sourceUri,
      Object columnFamilies) {
    TableId tableId = TableId.of(datasetName, tableName);
    FormatOptions bigTableFormatOptions = FormatOptions.bigtable(); 
    //Issue 1: need to give this guy columnFamilies...

    ExternalTableDefinition externalTableDefinition =
        ExternalTableDefinition.newBuilder(sourceUri, Schema.of(), bigTableFormatOptions)
        .build();
    //Issue 2: I need to provide a schema for the builder, but I don't have/need one
    //Issue 3: How do i set sourceFormat to BIGTABLE? No setter is provided by the builder

    TableInfo tableInfo =
        TableInfo.newBuilder(tableId, externalTableDefinition)
            .build();

    return bigquery.create(tableInfo);
  }
```

To summarize, there are 3 issues I am trying to solve:
1. Provide `columnFamilies` to the FormatOptions (Or BigtableOptions). This is critical, I cannot create my table without this...
2. Init a builder without having to provide a schema. For now I am just passing an empty one.
3. Pass a `sourceFormat` to the `ExternalTableDefinition`, this is also critical and required.

I have spend a very long time sifting through the Google source code, but there does not appear to be a way to accomplish this currently.
Is there another way to create an ExternalTableDefinition programmatically?

### PR DESCRIPTION
**Pull request by pmakani**
Fixes #6417

### CODE REVIEW

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumn.java [hunk 1]
```diff
@@ -93,7 +93,7 @@
     public abstract BigtableColumn build();
   }
 
-  static Builder newBuilder() {
+  public static Builder newBuilder() {
```
Comment (elharo) [inline google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumn.java]: Javadoc

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumnFamily.java [hunk 2]
```diff
@@ -90,7 +90,7 @@
     public abstract BigtableColumnFamily build();
   }
 
-  static Builder newBuilder() {
+  public static Builder newBuilder() {
```
Comment (elharo) [inline google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumnFamily.java]: Javadoc

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java [hunk 3]
```diff
@@ -40,7 +40,7 @@ public Boolean getReadRowkeyAsString() {
     return columnFamilies;
   }
 
-  static final class Builder {
+  public static final class Builder {
```
Comment (elharo) [inline google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java]: Javadoc

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java [hunk 4]
```diff
@@ -134,10 +139,16 @@ public static Builder newBuilder() {
 
   static BigtableOptions fromPb(com.google.api.services.bigquery.model.BigtableOptions options) {
     Builder builder = newBuilder();
-    builder.setIgnoreUnspecifiedColumnFamilies(options.getIgnoreUnspecifiedColumnFamilies());
-    builder.setReadRowkeyAsString(options.getReadRowkeyAsString());
-    builder.setColumnFamilies(
-        Lists.transform(options.getColumnFamilies(), BigtableColumnFamily.FROM_PB_FUNCTION));
+    if (null != options.getIgnoreUnspecifiedColumnFamilies()) {
```
Comment (elharo) [inline google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java]: reverse is more conventional; that is,

options != null

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java [hunk 5]
```diff
@@ -134,10 +139,16 @@ public static Builder newBuilder() {
...
+      builder.setIgnoreUnspecifiedColumnFamilies(options.getIgnoreUnspecifiedColumnFamilies());
+    }
+    if (null != options.getReadRowkeyAsString()) {
```
Comment (elharo) [inline google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java]: ditto

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java [hunk 6]
```diff
@@ -134,10 +139,16 @@ public static Builder newBuilder() {
...
+      builder.setReadRowkeyAsString(options.getReadRowkeyAsString());
+    }
+    if (null != options.getColumnFamilies()) {
```
Comment (elharo) [inline google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java]: ditto

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java (hunk 4 above)
Comment (elharo) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java]: It's unclear why null isn't allowed since that's the only reason to set Boolean instead of boolean

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java [hunk 7]
```diff
@@ -302,6 +302,25 @@ public static Builder newBuilder(String sourceUri, Schema schema, FormatOptions
     return newBuilder(ImmutableList.of(sourceUri), schema, format);
   }
 
+  /**
+   * Creates a builder for an ExternalTableDefinition object.
+   *
+   * @param sourceUri The fully-qualified URIs that point to your data in Google Cloud. For Google
```
Comment (elharo) [inline google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java]: The --> the

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumn.java (hunk 1 above)
Comment (pmakani) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumn.java]: Done.

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumnFamily.java (hunk 2 above)
Comment (pmakani) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableColumnFamily.java]: Done.

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java (hunk 3 above)
Comment (pmakani) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java]: Done.

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java (hunk 4 above)
Comment (pmakani) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java]: Done.

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java (hunk 5 above)
Comment (pmakani) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java]: Done.

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java (hunk 6 above)
Comment (pmakani) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigtableOptions.java]: Done.

File: google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java (hunk 7 above)
Comment (pmakani) [reply google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java]: Done.

**Comment by pmakani** [comment]
@shollyman PTAL.
