### PR TITLE
all: fix copyright header

### LINKED ISSUE #2758: all: license headers shouldn't have "All rights reserved"
Originally reported by @tswast 

Per https://opensource.google.com/docs/releasing/preparing/#include-license-file-and-source-code-headers the top line should be Copyright 2017 Google LLC (no All rights reserved.)

### PR DESCRIPTION
**Pull request by pongad**
Fixes #2758.

Change the copyright header of all manually-written files to
the recommended format. The copyright year is not changed.

Autogenerated files should be updated by the code generator.

Created by command below:
```shell
find -name '*.java' |
  xargs grep -FL 'Generated("by GAPIC' |
  xargs fr -f 'Copyright (\d\d\d\d).*' -t 'Copyright $1 Google LLC'`
```

### CODE REVIEW

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/MockBigtableInstanceAdmin.java [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright 2017, Google LLC All rights reserved.
```
Comment (garrettjonesgoogle) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/MockBigtableInstanceAdmin.java]: This is an auto-generated file. So are several package-info.java files and Test*.java files.

**Comment by pongad** [comment]
@garrettjonesgoogle PTAL. I think I got this right now

**Comment by garrettjonesgoogle** [comment]
LGTM
