### PR TITLE
Marked exceptions for create and deletes in DNS as non-idempotent.

### LINKED ISSUE #808: Investigate flaky DNS integration test
[This build](https://travis-ci.org/GoogleCloudPlatform/gcloud-java/builds/119298316) saw the integration test pass in two modules and fail in the third with the following issue:

```
Running com.google.gcloud.dns.it.ITDnsTest
Tests run: 12, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 114.627 sec <<< FAILURE! - in com.google.gcloud.dns.it.ITDnsTest
testInvalidChangeRequest(com.google.gcloud.dns.it.ITDnsTest)  Time elapsed: 24.69 sec  <<< ERROR!
com.google.gcloud.dns.DnsException: The 'entity.change.deletions[0]' resource named 'subdomain.gcldjvit-65ccc5a3-5403-47f3-94ee.com. (A)' does not exist.
	at com.google.gcloud.dns.it.ITDnsTest.testInvalidChangeRequest(ITDnsTest.java:652)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 
404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "The 'entity.change.deletions[0]' resource named 'subdomain.gcldjvit-65ccc5a3-5403-47f3-94ee.com. (A)' does not exist.",
    "reason" : "notFound"
  } ],
  "message" : "The 'entity.change.deletions[0]' resource named 'subdomain.gcldjvit-65ccc5a3-5403-47f3-94ee.com. (A)' does not exist."
}
	at com.google.gcloud.dns.it.ITDnsTest.testInvalidChangeRequest(ITDnsTest.java:652)
testListZones(com.google.gcloud.dns.it.ITDnsTest)  Time elapsed: 0.686 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
	at com.google.gcloud.dns.it.ITDnsTest.testListZones(ITDnsTest.java:379)
Results :
Failed tests: 
  ITDnsTest.testListZones:379 expected:<0> but was:<1>
Tests in error: 
  ITDnsTest.testInvalidChangeRequest:652 » Dns The 'entity.change.deletions[0]' ...
Tests run: 12, Failures: 1, Errors: 1, Skipped: 0
```

### PR DESCRIPTION
**Pull request by mderka**
Fixes #808, relates to #816 .

### CODE REVIEW

**Comment by mderka** [comment]
@aozarov PTAL

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java [hunk 1]
```diff
@@ -147,15 +162,15 @@ public BaseServiceException(int code, String message, String reason, boolean ide
...
-    return error != null && error(error).isRetryable(retryableErrors());
+  protected boolean isRetryable(boolean idempotent, GoogleJsonError error) {
+    return error != null && error(error).isRetryable(idempotent, retryableErrors());
   }
 
-  protected boolean isRetryable(IOException exception) {
+  protected boolean isRetryable(boolean idempotent, IOException exception) {
     if (exception instanceof GoogleJsonResponseException) {
-      return isRetryable(((GoogleJsonResponseException) exception).getDetails());
+      return isRetryable(idempotent, (((GoogleJsonResponseException) exception).getDetails()));
```
Comment (mziccard) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Codacy Issue found: [Useless parentheses.](https://www.codacy.com/app/mziccard/gcloud-java/file/2381910367/issues/source?bid=3123103&fileBranchId=3225961#l171)

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java [hunk 2]
```diff
@@ -62,16 +68,25 @@ public Integer code() {
...
     }
 
-    boolean isRetryable(Set<Error> retryableErrors) {
+    boolean isRetryable(boolean idempotent, Set<Error> retryableErrors) {
       for (Error retryableError : retryableErrors) {
-        if ((retryableError.code() == null || retryableError.code().equals(this.code()))
-            && (retryableError.reason() == null || retryableError.reason().equals(this.reason()))) {
+        boolean match = (retryableError.code() == null || retryableError.code().equals(this.code()))
+            && (retryableError.reason() == null || retryableError.reason().equals(this.reason()));
+        if (match && idempotent || match && retryableError.rejected()) {
```
Comment (aozarov) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: I would leave the condition as it was and just instead of `return true` have `return idempotent || retryableError.rejected()`

There is no reason to continue the loop once we have a match.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java [hunk 3]
```diff
@@ -123,7 +138,7 @@ public BaseServiceException(GoogleJsonError error, boolean idempotent) {
     this.code = error.getCode();
```
Comment (aozarov) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: I wonder if this one could call `this(error.getCode(), error.getMessage(), reason(error), idempotent)` instead?

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java [hunk 4]
```diff
@@ -147,15 +162,15 @@ public BaseServiceException(int code, String message, String reason, boolean ide
     return Collections.emptySet();
   }
 
-  protected boolean isRetryable(GoogleJsonError error) {
-    return error != null && error(error).isRetryable(retryableErrors());
+  protected boolean isRetryable(boolean idempotent, GoogleJsonError error) {
```
Comment (aozarov) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Instead of this method, which I think we should probably embed in the `isRetryable(boolean, IOException)` I think we should have `protected boolean isRetryable(boolean idempotent, Error error)`. default implementation would just delegated to `error.isRetryable(idempotent, retryableErrors())`.

Having that I would change the first constructor and the last constructor to call it instead.

File: gcloud-java-dns/src/main/java/com/google/gcloud/dns/DnsException.java [hunk 5]
```diff
@@ -31,16 +31,16 @@
...
-      new Error(500, null),
-      new Error(502, null),
-      new Error(503, null),
-      new Error(null, "userRateLimitExceeded"),
-      new Error(null, "rateLimitExceeded"));
+      new Error(429, null, true),
+      new Error(500, null, false),
+      new Error(502, null, false),
+      new Error(503, null, false),
+      new Error(null, "userRateLimitExceeded", true),
```
Comment (aozarov) [inline gcloud-java-dns/src/main/java/com/google/gcloud/dns/DnsException.java]: can these reasons be part of the previous error codes? If so, this is why you made the loop in Error iterate over all values?

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 1 above)
Comment (aozarov) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: We can fix that.

**Comment by aozarov** [comment]
Looks good! Few comments/suggestions for further cleanup.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 1 above)
Comment (mderka) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Fixed.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 2 above)
Comment (mderka) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Fixed.

File: gcloud-java-dns/src/main/java/com/google/gcloud/dns/DnsException.java (hunk 5 above)
Comment (mderka) [inline gcloud-java-dns/src/main/java/com/google/gcloud/dns/DnsException.java]: I am not sure. Both node and ruby are handling these explicitly without code. We cannot simulate these errors ourselves. We concluded before that this was a way to go.

No, it was not the reason. The match will be reported either way.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 4 above)
Comment (mderka) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Done.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 3 above)
Comment (mderka) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Seems viable. However, then we do not actually use the suggested `protected boolean isRetryable(boolean idempotent, Error error)` anywhere. Is there a reason for keeping it?

**Comment by mderka** [comment]
All done. PTAL

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java [hunk 6]
```diff
@@ -48,10 +48,16 @@
 
     private final Integer code;
     private final String reason;
+    private final boolean rejected;
 
     public Error(Integer code, String reason) {
+      this(code, reason, false);
+    }
+
+    public Error(Integer code, String reason, boolean rejected) {
```
Comment (mziccard) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Should we use this constructor also in other services when it applies? For instance also in storage we retry on `429—Too Many Requests`.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java [hunk 7]
```diff
@@ -62,17 +68,25 @@ public Integer code() {
     }
 
     /**
+     * Returns true if the error indicates that the API call was certainly not accepted by the
+     * server.
```
Comment (mziccard) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Maybe an example could help users understand what `rejected()` means? We could mention that `rejected()` can be `true` for rate limit exceeded exceptions.

**Comment by garrettjonesgoogle** [comment]
Hi,

I wanted to remark that create and delete are actually idempotent, and changing them to non-idempotent miscategorizes them. Create is idempotent because after the first or subsequent calls, the result is already "X exists"; Delete is idempotent because after the first or subsequent calls, the result is "X does not exist". The success or error returned to the client is a separate issue from the idempotency of the operation on the data. 

Here is an alternative that is slightly more complex, but would probably do what the client expects:

* On the first call, if the result is ALREADY_EXISTS, then fail with that.
* On the first call, if the result is a different but retryable error code, then do a retry.
* On the retry, if the result is ALREADY_EXISTS, then return success. (The assumption is that the first failure happened after successful creation on the server)

The only case that might be odd is if there is a failure to contact the service, but the entity was already created before, then the result will be a success even though per service semantics it should return ALREADY_EXISTS. I would imagine this should be pretty uncommon though, and should probably only happen when the entity was only very recently created.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 6 above)
Comment (aozarov) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: We probably should for completeness, however setting up rejected only matters if the operation is not idempotent.
When idempotent is false we will not retry even if there is a match with a retryable exception unless we know for
sure that the server didn't process the exception (`rejected == true`).

In Storage I think all the exception are thrown as `idempotent == true`, so technically this will not change much there.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 7 above)
Comment (aozarov) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Right, rate limit exceeded errors should be indicated as rejected.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java [hunk 8]
```diff
@@ -138,7 +146,7 @@ public BaseServiceException(int code, String message, String reason, boolean ide
     this.code = code;
     this.reason = reason;
     this.idempotent = idempotent;
-    this.retryable = idempotent && new Error(code, reason).isRetryable(retryableErrors());
+    this.retryable = new Error(code, reason).isRetryable(idempotent, retryableErrors());
```
Comment (aozarov) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: I think this code could be cleaned a little. I sent @mderka a small patch to consider.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java [hunk 9]
```diff
@@ -187,8 +197,8 @@ public boolean idempotent() {
   }
 
   /**
-   * Returns the service location where the error causing the exception occurred. Returns
-   * {@code null} if not set.
+   * Returns the service location where the error causing the exception occurred. Returns {@code
+   * null} if not set.
```
Comment (aozarov) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Nit, s/set/available/ ?

File: gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java [hunk 10]
```diff
@@ -61,7 +61,7 @@ public ManagedZone create(ManagedZone zone, Map<Option, ?> options) throws DnsEx
           .setFields(FIELDS.getString(options))
           .execute();
     } catch (IOException ex) {
-      throw translate(ex);
+      throw translate(ex, false);
```
Comment (aozarov) [inline gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java]: see @garrettjonesgoogle comment, which I partially agree with.

I think that means there is some more work to do, however for now I suggest to keep this as `true` and create a separate issue suggesting that some idempotent method may report a wrong exception when retried (such as in this case 'already exists'). 

The reason I think it is OK to retry it because the implication is just misreported error (e.g. 'already exists' instead of 500 or timeout). In either case the user will get an exception.

File: gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java [hunk 11]
```diff
@@ -103,7 +103,7 @@ public boolean deleteZone(String zoneName) throws DnsException {
       dns.managedZones().delete(this.options.projectId(), zoneName).execute();
       return true;
     } catch (IOException ex) {
-      DnsException serviceException = translate(ex);
+      DnsException serviceException = translate(ex, false);
```
Comment (aozarov) [inline gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java]: I think we can safely consider this as idempotent, no?

File: gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java [hunk 12]
```diff
@@ -148,7 +148,7 @@ public Change applyChangeRequest(String zoneName, Change changeRequest, Map<Opti
           .setFields(FIELDS.getString(options))
           .execute();
     } catch (IOException ex) {
-      throw translate(ex);
+      throw translate(ex, false);
```
Comment (aozarov) [inline gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java]: This change looks reasonable to me.

**Comment by aozarov** [comment]
@garrettjonesgoogle I agree conceptually with what you are suggesting (see my other comment). However for `create` I am not convinced that it is OK to hide from the user the fact that his "Create" was actually successful (it was not there before) or that it was already created (maybe with different values then provided).

I don't think that "The assumption is that the first failure happened after successful creation on the server" is always correct (it could have been created by a parallel call).

**Comment by garrettjonesgoogle** [comment]
@aozarov Good point about the entity possibly being created with different values than the current request. One option there is when the situation is ambiguous, then do a get call to the server to get the existing entity, and determine if the values are the same, and report back appropriately. It's definitely higher overhead and more complex (you will have made a minimum of 3 RPC calls - 1 failed create, one create resulting in already_exists, and 1 get call), but it would be more correct.

File: gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java (hunk 11 above)
Comment (mderka) [inline gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java]: I do not think so. It would be the same case as create. If a zone exists, it will be deleted with success (200) return value. If the zone does not exist, the service returns 404. So, if the socket times out but the delete is processed, the retry will receive in a subsequent call 404 and return `false` instead of `true`.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 7 above)
Comment (mderka) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Done.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 8 above)
Comment (mderka) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Patch applied. It is nice.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 9 above)
Comment (mderka) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Fixed.

File: gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java (hunk 12 above)
Comment (mderka) [inline gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java]: I am keeping this one.

File: gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java (hunk 6 above)
Comment (mderka) [inline gcloud-java-core/src/main/java/com/google/gcloud/BaseServiceException.java]: Create #924.

File: gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java (hunk 10 above)
Comment (mderka) [inline gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java]: I am switching it back to true. It should be handled within #924.

File: gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java (hunk 11 above)
Comment (mderka) [inline gcloud-java-dns/src/main/java/com/google/gcloud/dns/spi/DefaultDnsRpc.java]: I am switching it back to true. It should be handled within #924.

**Comment by mderka** [comment]
I created issue #924 to continue with the discussion.

I removed the conflicts and incorporated the comments. Ready to proceed.
