### PR TITLE
bigquery: loudly report invalid operations on dryruns

### LINKED ISSUE #2479: google-cloud-bigquery 0.25.0-beta BigQueryClient throws java.lang.NullPointerException: Required parameter jobId must be specified. When performing dry run query.
google-cloud-bigquery 0.25.0-beta

BigQuery bigQuery = BigQueryOptions.getDefaultInstance.getService
QueryRequest request = QueryRequest.newBuilder(sql).setDryRun(true).setUseLegacySql(false).build()
bigQuery.query(request)

Throws  java.lang.NullPointerException: Required parameter jobId must be specified.

### PR DESCRIPTION
**Pull request by pongad**
Fixes #2479.

### CODE REVIEW

File: google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java [hunk 1]
```diff
@@ -410,9 +415,34 @@ public Job reload(JobOption... options) {
...
+    QueryJobConfiguration config;
+    if (jobConfig instanceof QueryJobConfiguration) {
+      config = (QueryJobConfiguration) jobConfig;
+    } else {
+      return;
+    }
+
+    // Not "if (config.dryRun())", which fails if the Boolean is null.
+    // The below assumes that null means not-dryrun.
+    if (config.dryRun() == Boolean.TRUE) {
```
Comment (pongad) [inline google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java]: I just realized; this is incorrect. `Boolean.TRUE` does *not* compare equal to `new Boolean(true)`. I'll fix this
