### PR TITLE
Remove BlobListOption.recursive option and fix delimiter handling

### LINKED ISSUE #692: Support the delimiter parameter and prefixes result field for bucket listing
See [`delimiter`](https://cloud.google.com/storage/docs/json_api/v1/objects/list) - this is necessary to be able to list "directories".

In addition to `BlobListOption.delimiter(String)` it'd be nice if there were an argument-less method that uses `/` as the delimiter, since that's what ~99% of usages will want. I'd suggest `directories()` as that method name, so users can write `bucket.list("...", BlobListOption.directories())`.

### PR DESCRIPTION
**Pull request by mziccard**
This PR fixes #692 and does the following changes:
- Remove `BlobListOption.recursive` option
- Add `BlobListOption.currentDirectory` option that sets the '/' delimiter
- Add `isDirectory` method to `BlobInfo` objects
- Change `StorageRpc.list(bucket)` method to add prefixes to the list of storage objects
- Add unit and integration tests

### CODE REVIEW

File: gcloud-java-storage/src/main/java/com/google/gcloud/spi/DefaultStorageRpc.java [hunk 1]
```diff
@@ -163,8 +166,20 @@ public StorageObject create(StorageObject storageObject, final InputStream conte
           .setPageToken(PAGE_TOKEN.getString(options))
           .setFields(FIELDS.getString(options))
           .execute();
-      return Tuple.<String, Iterable<StorageObject>>of(
-          objects.getNextPageToken(), objects.getItems());
+      Iterable<StorageObject> storageObjects = Iterables.concat(
+          objects.getItems() != null ? objects.getItems() : ImmutableList.<StorageObject>of(),
```
Comment (aozarov) [inline gcloud-java-storage/src/main/java/com/google/gcloud/spi/DefaultStorageRpc.java]: [`MoreObjects.firstNonNull`](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/MoreObjects.html#firstNonNull(T,%20T)) could make it slightly nicer.

File: gcloud-java-storage/src/main/java/com/google/gcloud/storage/BlobInfo.java [hunk 2]
```diff
@@ -589,6 +601,18 @@ public Long updateTime() {
   }
 
   /**
+   * Returns {@code true} if the current blob represents a directory. This can only happen if the
+   * blob is returned by {@link Storage#list(String, Storage.BlobListOption...)} when the
+   * {@link Storage.BlobListOption#currentDirectory()} option is used. If {@code true} only
```
Comment (aozarov) [inline gcloud-java-storage/src/main/java/com/google/gcloud/storage/BlobInfo.java]: I would use `{@code true}` only when it is in a code context (e.g. boolean param, return type,...) but not when "true" is part of the sentence (and could be replaced with e.g. "this is the case").

File: gcloud-java-storage/src/main/java/com/google/gcloud/storage/BlobInfo.java [hunk 3]
```diff
@@ -761,6 +785,9 @@ public Acl apply(ObjectAccessControl objectAccessControl) {
         }
       }));
     }
+    if (storageObject.get("isDirectory") != null) {
```
Comment (aozarov) [inline gcloud-java-storage/src/main/java/com/google/gcloud/storage/BlobInfo.java]: If you don't care about the value you can use `containsKey`, no?

File: gcloud-java-storage/src/main/java/com/google/gcloud/storage/Storage.java [hunk 4]
```diff
@@ -694,10 +694,17 @@ public static BlobListOption prefix(String prefix) {
     }
 
     /**
-     * Returns an option to specify whether blob listing should include subdirectories or not.
+     * If specified, results are returned in a directory-like mode. Blobs whose names, aside from
```
Comment (aozarov) [inline gcloud-java-storage/src/main/java/com/google/gcloud/storage/Storage.java]: should we replace "aside from" with "after"?

File: gcloud-java-storage/src/main/java/com/google/gcloud/storage/StorageOptions.java [hunk 5]
```diff
@@ -137,7 +110,7 @@ public boolean equals(Object obj) {
       return false;
     }
     StorageOptions other = (StorageOptions) obj;
-    return baseEquals(other) && Objects.equals(pathDelimiter, other.pathDelimiter);
+    return baseEquals(other);
```
Comment (aozarov) [inline gcloud-java-storage/src/main/java/com/google/gcloud/storage/StorageOptions.java]: Alternative, `return obj instanceof StorageOptions && baseEquals((StorageOptions) obj)`

**Comment by aozarov** [comment]
Very nice! LGTM. Feel free to merge after taking care of the comments which you agree with.
