### PR TITLE
Fix logging integration test failure on when running on GCE

### LINKED ISSUE #3632: testLoggingHandler fails with error expected:<g[lobal]> but was:<g[ce_instance]>
URL https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-logging

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.google.cloud.logging.it.ITLoggingTest
Sep 01, 2018 12:36:24 AM com.google.cloud.logging.BaseSystemTest testLoggingHandler
INFO: Message
Sep 01, 2018 12:36:40 AM com.google.cloud.logging.BaseSystemTest testSyncLoggingHandler
WARNING: Message
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 21.369 sec <<< FAILURE! - in com.google.cloud.logging.it.ITLoggingTest
testLoggingHandler(com.google.cloud.logging.it.ITLoggingTest)  Time elapsed: 5.036 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<g[lobal]> but was:<g[ce_instance]>

Results :

Failed tests: 
  ITLoggingTest>BaseSystemTest.testLoggingHandler:315 expected:<g[lobal]> but was:<g[ce_instance]>

Tests run: 11, Failures: 1, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ google-cloud-logging ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.709 s
[INFO] Finished at: 2018-09-01T00:36:44+00:00
[INFO] Final Memory: 31M/86M
[INFO] ------------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by yihanzhen**
The `monitoredResource` for logging would contain information of the GCE instance when running on GCE. Change the hard-coded assertions to make the test pass when running on GCE as well as local environment. Fix #3632

### CODE REVIEW

**Comment by hzyi-google** [comment]
PTAL

File: google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/BaseSystemTest.java [hunk 1]
```diff
@@ -312,9 +312,11 @@ public void testLoggingHandler() throws InterruptedException {
     assertEquals(logId, entry.getLogName());
     assertEquals(ImmutableMap.of("levelName", "INFO",
```
Comment (pongad) [inline google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/BaseSystemTest.java]: You don't need to change everything in the file, but I think we should update these so that every assert in this test uses Truth.

**Comment by hzyi-google** [comment]
PTAL @pongad
