### PR TITLE
Fix setting ContentRange to inclusive positions

### LINKED ISSUE #373: DefaultStorageRpc.read setting wrong range
In [DefaultStorageRpc.read](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-storage/src/main/java/com/google/gcloud/spi/DefaultStorageRpc.java#L418) we set the content range as:
```java
public byte[] read(StorageObject from, Map<Option, ?> options, long position, int bytes)
    throws StorageException {
  ...
  downloader.setContentRange(position, (int) position + bytes);
  ...
}
```

Accorting to [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35) positions are inclusive, so we should probably do: `downloader.setContentRange(position, (int) position + bytes - 1);`

### PR DESCRIPTION
**Pull request by mziccard**
This fixes #373

### CODE REVIEW

File: gcloud-java-storage/src/main/java/com/google/gcloud/spi/DefaultStorageRpc.java [hunk 1]
```diff
@@ -415,7 +415,7 @@ public void onFailure(GoogleJsonError e, HttpHeaders responseHeaders) {
           .setIfGenerationMatch(IF_GENERATION_MATCH.getLong(options))
           .setIfGenerationNotMatch(IF_GENERATION_NOT_MATCH.getLong(options));
       MediaHttpDownloader downloader = req.getMediaHttpDownloader();
-      downloader.setContentRange(position, (int) position + bytes);
+      downloader.setContentRange(position, (int) position + bytes - 1);
```
Comment (aozarov) [inline gcloud-java-storage/src/main/java/com/google/gcloud/spi/DefaultStorageRpc.java]: Shall we do:
[Ints.checkedCast](http://docs.guava-libraries.googlecode.com/git/javadoc/src-html/com/google/common/primitives/Ints.html#line.87)(position + bytes - 1) until the http-api-client bug is fixed?

Comment (mziccard) [inline gcloud-java-storage/src/main/java/com/google/gcloud/spi/DefaultStorageRpc.java]: Sure, it should make it easier to identify errors. Fixed in place.
