### PR TITLE
Fix regression in storage url signing of objects with slashes in names

### LINKED ISSUE #1346: Regression in storage url signing
@ostronom @mziccard It seems #1277 has caused a regression in my code.  I use `/` characters in the blob names, and they are now being unexpectedly encoded as `%2F` in the signed path.

It seems that [object naming requirements](https://cloud.google.com/storage/docs/naming#objectnames) are not equivalent to URL encoding.

When I round-trip a signed url, `Storage#get` now fails to find the successfully uploaded file (confirmed via `gsutil` and Cloud Console). 

My understanding is that `/`s are valid characters for blob names. From the same page quoted above:

> The canonical resource is everything that follows the host name. For example, if the Cloud Storage URL is https://storage.googleapis.com/example-bucket/cat-pics/tabby.jpeg, then the canonical resource is /example-bucket/cat-pics/tabby.jpeg.

It seems like this library needs to use a different escape function for object names. (Also, I noticed that the new test `testSignUrlForBlobWithSpecialChars`, does not cover slashes.)

Does this make sense? What is the intended behavior for blob names containing slashes?

****

repro test:

```java
    BlobInfo blobInfo1 = BlobInfo.builder(bucketName, "foo/bar/baz #%20other cool stuff.txt").build();
    storage.create(blobInfo1, "content".getBytes());
    URL url = storage.signUrl(
        blobInfo1,
        1,
        TimeUnit.HOURS,
        httpMethod(HttpMethod.PUT),
        httpMethod(HttpMethod.GET)
    );
    final String[] split = url.getPath().split("/");
    Blob notFound = storage.get(split[1], split[2]); // unexpectedly null!
    Blob found = storage.get(split[1], URLDecoder.decode(split[2])); // found, surprisingly
```

### PR DESCRIPTION
**Pull request by mziccard**
This replaces #1347 and fixes #1346

@ostronom I took the liberty to cherry-pick your commits and apply some fixes, namely:
- Squash and rebase on top of master
- Handle `?` character: `UrlEscapers.urlFragmentEscaper()` does not escape `?`. Even though the use of `?` in blob names is discouraged (see [here](https://cloud.google.com/storage/docs/naming#objectnames)) we better handle it properly
- Add slashes and special characters to `signUrl` integration tests

@ostronom @lesv can you have a look?

### CODE REVIEW

**Comment by mziccard** [comment]
@mickeyreiss this should fix the regression, feel free to comment on :)

File: google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java [hunk 1]
```diff
@@ -528,7 +528,8 @@ public URL signUrl(BlobInfo blobInfo, long duration, TimeUnit unit, SignUrlOptio
     if (blobInfo.getName().startsWith("/")) {
       path.setLength(path.length() - 1);
     }
-    path.append(UrlEscapers.urlPathSegmentEscaper().escape(blobInfo.getName()));
+    String escapedName = UrlEscapers.urlFragmentEscaper().escape(blobInfo.getName());
+    path.append(escapedName.replace("?", "%3F"));
```
Comment (lesv) [inline google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java]: Do you need to do something with "&" here as well?

File: google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java [hunk 2]
```diff
@@ -1323,7 +1323,8 @@ public void testSignUrlForBlobWithSpecialChars() throws NoSuchAlgorithmException
       String blobName = "/a" + specialChar + "b";
       URL url =
           storage.signUrl(BlobInfo.newBuilder(BUCKET_NAME1, blobName).build(), 14, TimeUnit.DAYS);
-      String escapedBlobName = UrlEscapers.urlPathSegmentEscaper().escape(blobName);
+      String escapedBlobName =
+          UrlEscapers.urlFragmentEscaper().escape(blobName).replace("?", "%3F");
```
Comment (lesv) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java]: Do we also need to substitute "&amp;" for "&" ??

File: google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java [hunk 3]
```diff
@@ -1193,7 +1193,7 @@ public void testWriteChannelExistingBlob() throws IOException {
 
   @Test
   public void testGetSignedUrl() throws IOException {
-    String blobName = "test-get-signed-url-blob";
+    String blobName = "test-get-signed-url-blob/with/slashes/and?special=char*";
```
Comment (lesv) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITStorageTest.java]: Should this have a 2nd parameter &blah=this+is+a+test

File: google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java (hunk 2 above)
Comment (mickeyreiss) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java]: Did you consider configuring your own URL encoder, rather than implementing your own here?

Comment (mziccard) [inline google-cloud-storage/src/test/java/com/google/cloud/storage/StorageImplTest.java]: @lesv Escaping `&` is not necessary as long as we properly escape all `?`. See the improved integration test I pushed with 988c1c4

@mickeyreiss yours is a good refactoring suggestion that I plan on taking, however for the moment I say kick this out and fix the bug :D

**Comment by lesv** [comment]
LGTM
