### PR TITLE
Datastore fixes

### LINKED ISSUE #639: Expose consistency setting in LocalGcdHelper
The default is 0.9, but it's often useful to set it to 1.0 for test utility methods (i.e. clearing all entities using a non-ancestor query in between unit tests).

This can be set in [LocalGcdHelper.startGcd(..)](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/testing/LocalGcdHelper.java#L488) using the following option:

--consistency=...
The fraction of job application attempts that will succeed, with 0.0 resulting in no attempts succeeding, and 1.0 resulting in all attempts succeeding. Defaults to 0.9. Note that setting this to 1.0 may mask incorrect assumptions about the consistency of non-ancestor queries; non-ancestor queries are eventually consistent.

### LINKED ISSUE #640: Provide methods to set list values of the same type
For example, we could expose a method:
`set(String value1, String value2, String others...)` to create a `ListValue` of String Values instead of having to write:
`entityBuilder.set("property", StringValue.of("val1"), StringValue.of("val2"), ...)`

### LINKED ISSUE #642: Provide getter for a key's parent
The `BaseKey` `parent()` method's return type will be `BaseKey`, and the `IncompleteKey` and `Key` classes can override this method to return a parent of type `Key`.

### PR DESCRIPTION
**Pull request by ajkannan**
This PR:
- Fixes #639 (exposes consistency in LocalGcdHelper)
- Fixes #640 (provides set methods for lists containing only one type)
- Fixes #642 (provide getter for a key's parent)
- Cleans up the getList return value

### CODE REVIEW

File: gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/IncompleteKey.java [hunk 1]
```diff
@@ -84,6 +84,25 @@ static IncompleteKey fromPb(DatastoreV1.Key keyPb) {
     return new IncompleteKey(projectId, namespace, path);
   }
 
+  /**
+   * Returns the key's parent.
+   */
+  @Override
+  public Key parent() {
+    List<PathElement> ancestors = ancestors();
+    if (!ancestors.isEmpty()) {
```
Comment (aozarov) [inline gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/IncompleteKey.java]: Nit (style), I would check
```java
if(ancestors.isEmpty()) {
   return null;`
}
```
and avoid the indent of the rest of the code.

File: gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/IncompleteKey.java [hunk 2]
```diff
@@ -84,6 +84,25 @@ static IncompleteKey fromPb(DatastoreV1.Key keyPb) {
...
+      PathElement parent = ancestors.get(ancestors.size() - 1);
+      Key.Builder keyBuilder;
+      if (parent.hasName()) {
+        keyBuilder = Key.builder(projectId(), parent.kind(), parent.name());
+      } else {
+        keyBuilder = Key.builder(projectId(), parent.kind(), parent.id());
+      }
+      return keyBuilder.ancestors(ancestors.subList(0, ancestors.size() - 1)).build();
```
Comment (aozarov) [inline gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/IncompleteKey.java]: what about namespace?

File: gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/ListValue.java [hunk 3]
```diff
@@ -138,8 +139,8 @@ public static ListValue of(List<? extends Value<?>> values) {
     return new ListValue(values);
   }
 
-  public static ListValue of(Value<?> first, Value<?>... other) {
-    return new ListValue(first, other);
+  public static ListValue of(Value<?> first, Value<?> second, Value<?>... other) {
```
Comment (aozarov) [inline gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/ListValue.java]: Was this change necessary? What about a single value list?

File: gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java [hunk 4]
```diff
@@ -138,43 +139,120 @@ public B set(String name, String value) {
...
+    }
+
     public B set(String name, List<? extends Value<?>> values) {
       properties.put(name, of(values));
       return self();
     }
 
-    public B set(String name, Value<?> value, Value<?>... other) {
-      properties.put(name, of(value, other));
+    public B set(String name, Value<?> first, Value<?> second, Value<?>... other) {
```
Comment (aozarov) [inline gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java]: I don't think this change is necessary.

File: gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java [hunk 5]
```diff
@@ -183,6 +261,17 @@ public B set(String name, Blob value) {
       return self();
     }
 
+    public B set(String name, Blob first, Blob second, Blob... others) {
```
Comment (aozarov) [inline gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java]: Lets add javadoc (for all cases) to make it clear that this version is setting a list of values.

File: gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/testing/LocalGcdHelper.java [hunk 6]
```diff
@@ -590,10 +600,13 @@ public static void main(String... args) throws IOException, InterruptedException
     String action = parsedArgs.get("action");
     int port =
         (parsedArgs.get("port") == null) ? DEFAULT_PORT : Integer.parseInt(parsedArgs.get("port"));
+    double consistency =
```
Comment (aozarov) [inline gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/testing/LocalGcdHelper.java]: this could be moved to be part of the "START" case.

File: gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java (hunk 4 above)
Comment (ajkannan) [inline gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java]: Because of [this overloaded set](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java#L131) method, I believe it's impossible to set a list with one value at the moment.

**Comment by ajkannan** [comment]
Incorporated the comments, ready for another pass.

File: gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java (hunk 4 above)
Comment (aozarov) [inline gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java]: Right, luckily we have the set that accepts a list which will support the singleton case, no?

**Comment by ajkannan** [comment]
Removed unnecessary changes to ListValue and made addValue() unambiguous.
