### PR TITLE
Fix IllegalArgumentException when OPTIONS in cors

### LINKED ISSUE #177: IllegalArgumentException when Cors contain OPTIONS
When we try to get a bucket that has OPTIONS among its `cors` methods the following exception is thrown:
> java.lang.IllegalArgumentException: No enum constant com.google.gcloud.storage.HttpMethod.OPTIONS

### PR DESCRIPTION
**Pull request by mziccard**
This PR fixes #177.

### CODE REVIEW

File: gcloud-java-storage/src/main/java/com/google/gcloud/storage/HttpMethod.java [hunk 1]
```diff
@@ -20,5 +20,5 @@
  * Http method supported by Storage service.
  */
 public enum HttpMethod {
-  GET, HEAD, PUT, POST, DELETE
+  GET, HEAD, PUT, POST, DELETE, OPTIONS
```
Comment (aozarov) [inline gcloud-java-storage/src/main/java/com/google/gcloud/storage/HttpMethod.java]: Interesting. I am not sure where I got the original list though I think it is from [here](https://cloud.google.com/storage/docs/xml-api/get-bucket-cors?hl=en).
Maybe we should put all possible methods based on the [RFC](https://tools.ietf.org/html/rfc2616#section-5.1.1), which is referenced from [here](http://www.w3.org/TR/cors/#http-access-control-request-method)?

Comment (mziccard) [inline gcloud-java-storage/src/main/java/com/google/gcloud/storage/HttpMethod.java]: If you look [here](https://cloud.google.com/storage/docs/json_api/v1/buckets) it seems that OPTIONS is considered a valid value as well. I experienced the error while listing buckets of a project of mine, so a bucket with `OPTIONS` as cors method can exist :)

We could add all of them even though I don't think `TRACE` and ``CONNECT` have any use here. Adding all of them until we figure out wich ones are really used will do no harm.

Comment (aozarov) [inline gcloud-java-storage/src/main/java/com/google/gcloud/storage/HttpMethod.java]: Ok, according to @BrandonY from GCS there is no need to include `TRACE` and `CONNECT`.
